CREATE TABLE `operational_records` (`id` int AUTO_INCREMENT NOT NULL, `ownerUserId` int NOT NULL, `targetUserId` int NOT NULL, `kind` enum('sparring','lista','migracao','ativacao','onboarding') NOT NULL, `payloadJson` text NOT NULL, `sourceFileName` varchar(255) NOT NULL DEFAULT '', `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT `operational_records_id` PRIMARY KEY(`id`), CONSTRAINT `operational_records_owner_kind_target_uq` UNIQUE(`ownerUserId`,`targetUserId`,`kind`));--> statement-breakpoint
CREATE TABLE `onda_duos` (`id` int AUTO_INCREMENT NOT NULL, `createdByUserId` int NOT NULL, `firstUserId` int NOT NULL, `secondUserId` int NOT NULL, `days` varchar(120) NOT NULL, `meeting` varchar(120) NOT NULL, `plan` text NOT NULL, `target` int NOT NULL DEFAULT 25, `createdAt` timestamp NOT NULL DEFAULT (now()), CONSTRAINT `onda_duos_id` PRIMARY KEY(`id`));--> statement-breakpoint
ALTER TABLE `operational_records` ADD CONSTRAINT `operational_records_ownerUserId_users_id_fk` FOREIGN KEY (`ownerUserId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `operational_records` ADD CONSTRAINT `operational_records_targetUserId_users_id_fk` FOREIGN KEY (`targetUserId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `onda_duos` ADD CONSTRAINT `onda_duos_createdByUserId_users_id_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `onda_duos` ADD CONSTRAINT `onda_duos_firstUserId_users_id_fk` FOREIGN KEY (`firstUserId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `onda_duos` ADD CONSTRAINT `onda_duos_secondUserId_users_id_fk` FOREIGN KEY (`secondUserId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `onda_duos_first_idx` ON `onda_duos` (`firstUserId`);--> statement-breakpoint
CREATE INDEX `onda_duos_second_idx` ON `onda_duos` (`secondUserId`);
