import { useState } from "react";
import { MailPlus, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
export default function AdminInvitePanel(){
 const [name,setName]=useState("Kellen"); const [email,setEmail]=useState("peauguda@gmail.com"); const [result,setResult]=useState<{inviteUrl:string;email:string}|null>(null);
 const invite=trpc.admin.inviteNavigator.useMutation({onSuccess:r=>{setResult(r);toast.success("Convite enviado com código de confirmação.")},onError:e=>toast.error(e.message)});
 return <div className="space-y-6"><section className="rounded-3xl bg-[#15382f] p-7 text-white md:p-10"><span className="inline-flex items-center gap-2 rounded-full border border-amber-100/20 bg-white/5 px-3 py-1 font-mono text-[10px] tracking-[.15em] text-amber-100"><ShieldCheck size={13}/> ADMINISTRAÇÃO NOVA</span><h2 className="mt-5 text-4xl font-semibold tracking-[-.06em]">Convidar navegante.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-emerald-50/70">Crie apenas o acesso pendente. A pessoa confirma o próprio e-mail e define a própria senha. O cadastro público permanece fechado.</p></section><section className="max-w-2xl rounded-2xl border border-emerald-100 bg-white p-6"><div className="flex items-center gap-3"><MailPlus className="text-emerald-700"/><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-700">CONVITE INDIVIDUAL</p><h3 className="text-xl font-semibold">Novo acesso privado</h3></div></div><div className="mt-5 grid gap-4"><label className="grid gap-1 text-xs">Nome de exibição<Input value={name} onChange={e=>setName(e.target.value)}/></label><label className="grid gap-1 text-xs">E-mail<Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label></div><Button className="mt-5 bg-[#0e3426]" disabled={invite.isPending} onClick={()=>invite.mutate({name,email})}><MailPlus size={16}/>{invite.isPending?"Enviando...":"Enviar convite"}</Button>{result&&<div className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm"><b>Convite enviado para {result.email}</b><p className="mt-1 text-emerald-900/65">O código expira em 15 minutos. Reenviar gera um novo código sem duplicar a conta.</p><a className="mt-3 block break-all font-mono text-xs font-semibold text-emerald-800 underline" href={result.inviteUrl}>{new URL(result.inviteUrl,window.location.origin).href}</a></div>}</section></div>;
}
