import { trpc } from "@/lib/trpc";
import { ArrowRight, BookOpenCheck, Dumbbell, Flame, Gauge, GraduationCap, Crown, ShieldCheck, Sparkles, Swords, Target } from "lucide-react";

type Destination = "jornada";
type Area = { key:string; label:string; score:number; focus:string };
type Mission = { id:string; title:string; done:boolean; xp:number; area:string };
type Journey = { areas?:Area[]; missions?:Mission[]; checkins?:{date:string;energy:number;reflection:string;nextAction:string}[]; cycleGoal?:string; xp?:number };

const disciplines = [
  { key:"profissional", title:"Estratégia em campo", icon:Target, description:"Transforme meta em prioridade, ação observável e evidência.", drills:["Escolha uma meta de 7 dias", "Defina o primeiro gesto de 15 minutos", "Registre o resultado sem justificar"] },
  { key:"pessoal", title:"Ritmo e disciplina", icon:Dumbbell, description:"Construa um ritmo possível mesmo nos dias de pouca energia.", drills:["Proteja um bloco curto na agenda", "Reduza a ação até ficar executável", "Repita antes de aumentar a carga"] },
  { key:"emocional", title:"Presença sob pressão", icon:Gauge, description:"Reconheça o estado interno antes de decidir o próximo passo.", drills:["Nomeie a emoção sem julgamento", "Separe fato de interpretação", "Escolha uma resposta consciente"] },
  { key:"comunidade", title:"Força em formação", icon:ShieldCheck, description:"Aprenda em conjunto e devolva valor para a sua comunidade.", drills:["Peça uma perspectiva honesta", "Compartilhe um aprendizado útil", "Reconheça quem ajudou na travessia"] },
];

export default function EspartaPanel({ onNavigate }: { onNavigate:(view:Destination)=>void }) {
  const journey = trpc.agent.journey.useQuery();
  const state = (journey.data?.state || {}) as Journey;
  const areas = state.areas || [];
  const weakest = [...areas].sort((a,b)=>a.score-b.score)[0];
  const strongest = [...areas].sort((a,b)=>b.score-a.score)[0];
  const active = disciplines.find(item=>item.key===weakest?.key) || disciplines[0];
  const completed = state.missions?.filter(item=>item.done).length || 0;
  const total = state.missions?.length || 0;
  const logs = state.checkins || [];
  const averageEnergy = logs.length ? (logs.reduce((sum,item)=>sum+item.energy,0)/logs.length).toFixed(1) : "-";
  const readiness = areas.length ? Math.round(areas.reduce((sum,item)=>sum+item.score,0)/areas.length*10) : 0;
  const forgeSteps = active.drills.map((title,index)=>({ title, done:index===0 && completed>0 }));

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl border border-amber-200/20 bg-[#301c16] p-7 text-white shadow-xl md:p-10">
      <div className="absolute inset-x-0 top-0 h-2 bg-[repeating-linear-gradient(90deg,#d8b967_0_16px,transparent_16px_23px,#d8b967_23px_31px,transparent_31px_38px)] opacity-55"/>
      <div className="absolute -right-20 -top-24 h-80 w-80 rounded-full border-[42px] border-red-200/10"/>
      <Swords className="absolute bottom-4 right-8 hidden rotate-[-8deg] text-amber-100/10 md:block" size={190} strokeWidth={.65}/>
      <div className="absolute right-16 top-12 hidden h-24 w-24 place-items-center rounded-full border-2 border-amber-200/25 bg-amber-100/5 md:grid"><Crown size={48} className="text-amber-100/30"/></div>
      <div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-amber-100/25 bg-white/5 px-3 py-1 font-mono text-[10px] tracking-[.15em] text-amber-100"><ShieldCheck size={13}/> PORTAL ESPARTA</span><h2 className="mt-5 text-4xl font-semibold tracking-[-.06em] md:text-5xl">Clareza mostra o caminho.<br/>Treino sustenta a travessia.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-amber-50/70">Esparta lê os sinais da sua Jornada, aponta o território que pede atenção e monta uma Forja prática. Não é diagnóstico clínico: é uma leitura de desenvolvimento baseada no que você registrou.</p><div className="mt-6 flex flex-wrap gap-2"><span className="rounded-full border border-amber-100/20 bg-amber-50/10 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">AGOGÊ · TREINO</span><span className="rounded-full border border-amber-100/20 bg-amber-50/10 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">ARETÊ · EXCELÊNCIA</span><span className="rounded-full border border-amber-100/20 bg-amber-50/10 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">ANDREÍA · CORAGEM</span></div></div>
    </section>

    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-red-100 bg-white p-5"><Flame className="text-red-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-red-700">TERRITÓRIO DE TREINO</p><b className="mt-1 block text-2xl">{weakest?.label || "Faça a Vida 360"}</b><p className="mt-2 text-sm text-emerald-900/60">{weakest ? `${weakest.score}/10 · ${weakest.focus}` : "Suas notas dão direção à Forja."}</p></article><article className="rounded-2xl border border-amber-100 bg-white p-5"><ShieldCheck className="text-amber-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-amber-700">FORÇA DE APOIO</p><b className="mt-1 block text-2xl">{strongest?.label || "Ainda não revelada"}</b><p className="mt-2 text-sm text-emerald-900/60">{strongest ? `${strongest.score}/10 · use esta força para apoiar o treino.` : "Avalie suas áreas para reconhecer recursos."}</p></article><article className="rounded-2xl border border-emerald-100 bg-white p-5"><Gauge className="text-emerald-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-emerald-700">PRONTIDÃO REGISTRADA</p><b className="mt-1 block text-3xl">{readiness}%</b><p className="mt-2 text-sm text-emerald-900/60">energia média {averageEnergy} · {completed}/{total} missões concluídas</p></article></section>

    <section className="grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><article className="rounded-2xl bg-[#15382f] p-6 text-white"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-amber-200 text-emerald-950"><active.icon/></span><div><p className="font-mono text-[10px] tracking-[.12em] text-amber-200">PDI SUGERIDO</p><h3 className="text-2xl font-semibold">{active.title}</h3></div></div><p className="mt-5 text-sm leading-7 text-emerald-50/75">{active.description}</p><div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4"><small className="font-mono text-[9px] tracking-[.12em] text-amber-200">OBJETIVO DO CICLO</small><p className="mt-2 text-sm leading-6">{state.cycleGoal || "Defina uma meta de 30 dias em Minha Jornada para dar contexto ao plano."}</p></div><button onClick={()=>onNavigate("jornada")} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-amber-200">Revisar diagnóstico na Jornada <ArrowRight size={16}/></button></article>
    <article className="rounded-2xl border border-red-100 bg-white p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.12em] text-red-700">FORJA AUTOMÁTICA</p><h3 className="mt-1 text-2xl font-semibold">Treino de 3 movimentos</h3><p className="mt-2 text-sm leading-6 text-emerald-900/60">Gerado a partir da área com menor nota. Refaça a Vida 360 para recalibrar.</p></div><GraduationCap className="shrink-0 text-red-700" size={30}/></div><div className="mt-5 space-y-3">{forgeSteps.map((step,index)=><div key={step.title} className={`flex gap-4 rounded-xl border p-4 ${step.done ? "border-emerald-200 bg-emerald-50" : "border-red-100 bg-red-50/40"}`}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full font-mono text-sm ${step.done ? "bg-emerald-700 text-white" : "bg-red-100 text-red-800"}`}>{index+1}</span><div><b className="text-sm">{step.title}</b><p className="mt-1 text-xs leading-5 text-emerald-900/55">{index===0 ? "Preparação · faça hoje" : index===1 ? "Prática · repita por 3 dias" : "Integração · registre a evidência"}</p></div></div>)}</div></article></section>

    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-amber-100 bg-amber-50 p-6"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-amber-200 text-emerald-950"><Sparkles/></span><div><p className="font-mono text-[10px] tracking-[.12em] text-amber-800">CRITÉRIO DE EVOLUÇÃO</p><h3 className="mt-1 text-xl font-semibold">Evidência antes de intensidade.</h3><p className="mt-2 text-sm leading-7 text-emerald-950/65">Considere o treino concluído quando houver uma ação observável e um registro do que mudou. A Forja orienta, mas não substitui apoio profissional quando ele for necessário.</p></div></div></article><article className="rounded-2xl border border-emerald-100 bg-white p-6"><div className="flex items-center gap-3"><BookOpenCheck className="text-emerald-700"/><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-700">FECHAR O CICLO</p><h3 className="text-xl font-semibold">Treinar, observar, ajustar.</h3></div></div><p className="mt-4 text-sm leading-7 text-emerald-950/65">Depois do treino, registre no Diário de Bordo o fato, o aprendizado e a próxima ação. Esse registro recalibra a leitura do portal.</p><button onClick={()=>onNavigate("jornada")} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-emerald-800">Registrar evidência <ArrowRight size={16}/></button></article></section>
  </div>;
}
