import { trpc } from "@/lib/trpc";
import EvidenceForm from "@/components/EvidenceForm";
import { Anchor, ArrowRight, BookOpenCheck, Castle, CheckCircle2, Home, KeyRound, Landmark, Route, Sparkles, Users } from "lucide-react";

type Destination = "jornada" | "historia";
type Journey = { calling?:string; cycleGoal?:string; stage?:string; xp?:number; streak?:number; missions?:{done:boolean}[]; checkins?:{date:string;reflection:string;nextAction:string}[] };
export default function ItacaPanel({ onNavigate }: { onNavigate:(view:Destination)=>void }) {
 const journey=trpc.agent.journey.useQuery(); const state=(journey.data?.state||{}) as Journey; const missions=state.missions||[]; const completed=missions.filter(x=>x.done).length; const latest=state.checkins?.[0]; const returning=state.stage==="Retorno" || (state.xp||0)>=3500;
 return <div className="space-y-6">
  <section className="relative overflow-hidden rounded-3xl border border-amber-200/25 bg-[#12362d] p-7 text-white shadow-xl md:p-10"><div className="absolute inset-x-0 top-0 h-2 bg-[repeating-linear-gradient(90deg,#edd58b_0_15px,transparent_15px_22px,#edd58b_22px_29px,transparent_29px_36px)] opacity-55"/><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full border-[42px] border-emerald-100/10"/><Landmark className="absolute bottom-5 right-9 hidden text-amber-100/10 md:block" size={190} strokeWidth={.65}/><div className="absolute right-16 top-12 hidden h-24 w-24 place-items-center rounded-full border-2 border-amber-200/25 bg-white/5 md:grid"><Home size={46} className="text-amber-100/30"/></div><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-amber-100/25 bg-white/5 px-3 py-1 font-mono text-[10px] tracking-[.15em] text-amber-100"><Anchor size={13}/> PORTAL ÍTACA</span><h2 className="mt-5 text-4xl font-semibold tracking-[-.06em] md:text-5xl">Toda jornada muda você.<br/>O retorno mostra como.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-emerald-50/70">Ítaca é o portal de integração. Reúna o que aprendeu, reconheça quem se tornou e escolha o que volta com você para a vida cotidiana.</p><div className="mt-6 flex flex-wrap gap-2"><span className="rounded-full border border-amber-100/20 bg-white/5 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">NÓSTOS · RETORNO</span><span className="rounded-full border border-amber-100/20 bg-white/5 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">OÎKOS · LAR</span><span className="rounded-full border border-amber-100/20 bg-white/5 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">KOINONÍA · COMUNIDADE</span></div></div></section>
  <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-emerald-100 bg-white p-5"><Route className="text-emerald-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-emerald-700">TRAVESSIA</p><b className="mt-1 block text-3xl">{completed}/{missions.length}</b><p className="mt-2 text-sm text-emerald-900/60">provas concluídas no ciclo</p></article><article className="rounded-2xl border border-amber-100 bg-white p-5"><KeyRound className="text-amber-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-amber-700">CHAVE DO RETORNO</p><b className="mt-1 block text-2xl">{returning?"Integrar":"Ainda em travessia"}</b><p className="mt-2 text-sm text-emerald-900/60">{state.stage||"Chamado"} · {state.xp||0} XP</p></article><article className="rounded-2xl border border-sky-100 bg-white p-5"><BookOpenCheck className="text-sky-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-sky-700">MEMÓRIA VIVA</p><b className="mt-1 block text-3xl">{state.checkins?.length||0}</b><p className="mt-2 text-sm text-emerald-900/60">registros no Diário de Bordo</p></article></section>
  <section className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border border-emerald-100 bg-white p-6"><p className="font-mono text-[10px] tracking-[.12em] text-emerald-700">O QUE VOLTA COM VOCÊ</p><h3 className="mt-2 text-2xl font-semibold">Transforme experiência em princípio.</h3><div className="mt-5 grid gap-3"><div className="rounded-xl bg-[#f4f3ec] p-4"><b>1. Aprendizado</b><p className="mt-1 text-sm text-emerald-900/60">{latest?.reflection||"Registre a experiência que merece ser lembrada."}</p></div><div className="rounded-xl bg-[#f4f3ec] p-4"><b>2. Continuidade</b><p className="mt-1 text-sm text-emerald-900/60">{latest?.nextAction||"Escolha o hábito ou compromisso que seguirá com você."}</p></div><div className="rounded-xl bg-[#f4f3ec] p-4"><b>3. Partilha</b><p className="mt-1 text-sm text-emerald-900/60">Nomeie quem pode receber valor do que você aprendeu.</p></div></div><EvidenceForm tone="amber" context="Ítaca: registro de retorno" button="Completar meu registro" preset="itaca"/></article><article className="rounded-2xl bg-[#3b2b1b] p-6 text-white"><Castle className="text-amber-200" size={36}/><p className="mt-5 font-mono text-[10px] tracking-[.12em] text-amber-200">PACTO DE ÍTACA</p><h3 className="mt-2 text-2xl font-semibold">Voltar diferente, sem abandonar quem você é.</h3><p className="mt-4 text-sm leading-7 text-amber-50/70">Seu Chamado: {state.calling||"ainda não declarado"}</p><div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4"><small className="text-amber-100/55">Meta do ciclo</small><b className="mt-2 block leading-6">{state.cycleGoal||"Defina uma transformação para dar forma ao retorno."}</b></div></article></section>
  <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-4"><Sparkles className="shrink-0 text-amber-700"/><div><p className="font-mono text-[10px] tracking-[.12em] text-amber-800">RITUAL DE CHEGADA</p><h3 className="mt-1 text-xl font-semibold">Reconhecer. Agradecer. Devolver.</h3><p className="mt-2 text-sm leading-7 text-emerald-950/65">Escolha uma conquista, agradeça a quem sustentou a travessia e compartilhe uma prática que possa ajudar outra pessoa.</p></div></div></article><article className="rounded-2xl border border-emerald-100 bg-white p-6"><div className="flex items-center gap-3"><Users className="text-emerald-700"/><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-700">RETORNO À COMUNIDADE</p><h3 className="text-xl font-semibold">O aprendizado termina quando circula.</h3></div></div><p className="mt-4 text-sm leading-7 text-emerald-950/65">Não é preciso ensinar tudo. Uma conversa honesta, um exemplo ou uma ajuda concreta já transforma experiência em contribuição.</p><button onClick={()=>onNavigate("historia")} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-emerald-800"><CheckCircle2 size={16}/> Entender o Retorno na História</button></article></section>
 </div>;
}
