import { Anchor, BookOpen, CheckCircle2, Compass, Flag, Map, Route, ShipWheel, Sparkles, Target } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Destination = "jornada" | "historia";
type Journey = { calling?:string; cycleGoal?:string; stage?:"Chamado"|"Provação"|"Maestria"|"Retorno"; xp?:number; streak?:number; areas?:{key:string;label:string;score:number;focus:string}[]; missions?:{id:string;title:string;done:boolean;xp:number}[]; checkins?:{date:string}[] };
const stageCopy = {
  Chamado: { position:"No cais de partida", guidance:"Dê nome ao norte e escolha o primeiro gesto que prova sua decisão." },
  Provação: { position:"Em mar aberto", guidance:"Proteja o ritmo. Uma prova por vez, uma evidência por dia." },
  Maestria: { position:"Lendo ventos e estrelas", guidance:"Transforme experiência em método e compartilhe o que aprendeu." },
  Retorno: { position:"Rumo a Ítaca", guidance:"Integre a mudança à vida e devolva valor à sua comunidade." },
};

export default function NavegantePanel({ onNavigate }: { onNavigate:(view:Destination)=>void }) {
  const journey = trpc.agent.journey.useQuery();
  const state = (journey.data?.state || {}) as Journey;
  const stage = state.stage || "Chamado";
  const areas = state.areas || [];
  const attention = [...areas].sort((a,b)=>a.score-b.score)[0];
  const completed = state.missions?.filter(item=>item.done).length || 0;
  const total = state.missions?.length || 0;
  const logCount = state.checkins?.length || 0;
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl bg-[#08263b] p-7 text-white shadow-xl md:p-10"><div className="absolute -right-14 -top-16 h-72 w-72 rounded-full border-[38px] border-sky-200/10"/><ShipWheel className="absolute bottom-8 right-10 hidden text-sky-200/15 md:block" size={170} strokeWidth={.7}/><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-sky-200/25 bg-white/5 px-3 py-1 font-mono text-[10px] tracking-[.15em] text-sky-200"><Anchor size={13}/> PORTAL NAVEGANTE</span><h2 className="mt-5 text-4xl font-semibold tracking-[-.06em] md:text-5xl">Você não controla o mar.<br/>Mas pode escolher o rumo.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-sky-100/70">Seu painel de orientação reúne norte, posição atual, equilíbrio e o próximo movimento. Volte aqui quando precisar enxergar a rota inteira.</p></div></section>
    <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-sky-100 bg-white p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] tracking-[.12em] text-sky-700">CARTA DE NAVEGAÇÃO</p><h3 className="mt-1 text-2xl font-semibold">Seu norte declarado</h3></div><Compass className="text-sky-700"/></div><div className="mt-5 rounded-xl bg-sky-50 p-5"><small className="font-mono text-[9px] tracking-[.12em] text-sky-700">CHAMADO</small><p className="mt-2 text-lg font-semibold leading-7">{state.calling || "Defina seu Chamado para acender o farol."}</p></div><div className="mt-3 rounded-xl border border-emerald-100 p-5"><small className="font-mono text-[9px] tracking-[.12em] text-emerald-700">META DO CICLO</small><p className="mt-2 text-sm leading-6 text-emerald-900/75">{state.cycleGoal || "Escolha a transformação dos próximos 30 dias."}</p></div><button onClick={()=>onNavigate("jornada")} className="mt-4 text-sm font-semibold text-sky-700">Ajustar minha rota →</button></article>
    <article className="rounded-2xl bg-[#0b3b31] p-6 text-white"><p className="font-mono text-[10px] tracking-[.12em] text-amber-200">POSIÇÃO ATUAL</p><div className="mt-4 flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-full bg-amber-200 text-emerald-950"><Map/></span><div><b className="block text-2xl">{stage}</b><small className="text-emerald-100/65">{stageCopy[stage].position}</small></div></div><p className="mt-6 text-sm leading-7 text-emerald-50/80">{stageCopy[stage].guidance}</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/8 p-4"><small className="text-emerald-100/55">Experiência</small><b className="mt-1 block text-2xl">{state.xp || 0} XP</b></div><div className="rounded-xl bg-white/8 p-4"><small className="text-emerald-100/55">Retorno</small><b className="mt-1 block text-2xl">{state.streak || 0} dia(s)</b></div></div><button onClick={()=>onNavigate("historia")} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-amber-200"><BookOpen size={16}/> Entender este capítulo</button></article></section>
    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-emerald-100 bg-white p-5"><Route className="text-emerald-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-emerald-600">TRAVESSIA DA SEMANA</p><b className="mt-1 block text-3xl">{completed}/{total}</b><p className="mt-2 text-sm text-emerald-900/60">missões concluídas</p></article><article className="rounded-2xl border border-amber-100 bg-white p-5"><Target className="text-amber-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-amber-700">ÁREA QUE PEDE FAROL</p><b className="mt-1 block text-xl">{attention?.label || "Vida 360"}</b><p className="mt-2 text-sm text-emerald-900/60">{attention ? `${attention.score}/10 · ${attention.focus}` : "Avalie suas quatro dimensões."}</p></article><article className="rounded-2xl border border-sky-100 bg-white p-5"><BookOpen className="text-sky-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-sky-700">DIÁRIO DE BORDO</p><b className="mt-1 block text-3xl">{logCount}</b><p className="mt-2 text-sm text-emerald-900/60">evidências registradas</p></article></section>
    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-amber-200 text-emerald-950"><Sparkles/></span><div><p className="font-mono text-[10px] tracking-[.12em] text-amber-800">PRÓXIMO MOVIMENTO</p><b className="mt-1 block text-lg">{completed < total ? "Conclua uma missão que mova sua rota hoje." : logCount === 0 ? "Registre a primeira evidência no Diário de Bordo." : "Revise o norte e escolha uma nova prova consciente."}</b><button onClick={()=>onNavigate("jornada")} className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-emerald-800"><CheckCircle2 size={16}/> Ir para Minha Jornada</button></div></div></section>
  </div>;
}
