import { Button } from "@/components/ui/button";
import { useState } from "react";
import { BarChart3, BookOpen, CalendarDays, CheckCircle2, Compass, FileText, Flag, Medal, PlayCircle, SearchCheck, Sparkles, Target, Users } from "lucide-react";
import { ItakaEmblem, NordicCompassEmblem, SpartacusEmblem, TrojanHorseEmblem } from "@/components/emblems";

type TutorialStep = { id: string; title: string; subtitle: string; icon: typeof Target; color: string; what: string; how: string; impact: string };

const steps: TutorialStep[] = [
  { id: "painel", title: "Comece pelo Gestão", subtitle: "Seu ponto de partida", icon: Target, color: "bg-emerald-50 text-emerald-700", what: "Veja seus KPIs, a mensagem de Ítaka, novidades, Boas Práticas e o que merece atenção.", how: "Abra Gestão no início do dia e escolha uma ação concreta para executar.", impact: "Mais clareza, menos dispersão e uma rotina que começa pelo que realmente importa." },
  { id: "psv", title: "Planeje a PSV", subtitle: "Transforme meta em agenda", icon: CheckCircle2, color: "bg-lime-50 text-lime-800", what: "Organize o funil privado, oportunidades preparadas, tarefas, propostas e TPV da semana.", how: "Cadastre clientes, selecione oportunidades e salve o Ritual PSV com resultado, plano e roteiro.", impact: "Você troca intenção por próximos passos visíveis e mensuráveis." },
  { id: "prospeccao", title: "Use o Cavalo de Tróia", subtitle: "Chegue preparado", icon: TrojanHorseEmblem, color: "bg-amber-50 text-amber-900", what: "Crie dossiês, consulte CNPJ sob ação explícita e registre hipóteses antes da visita.", how: "Pesquise o cliente, confirme fatos públicos e escreva a abordagem antes de contatar.", impact: "Conversas mais relevantes, menos improviso e mais confiança comercial." },
  { id: "nordica", title: "Oriente-se pela Estratégia", subtitle: "Priorize território e ativação", icon: NordicCompassEmblem, color: "bg-cyan-50 text-cyan-900", what: "Acompanhe microrrotas, funil quente, carteira autorizada e checklist de ativações.", how: "Importe a carteira, salve a importação, selecione prioridades e atualize cada avanço.", impact: "Mais consistência no campo e uma visão real do que está acontecendo com cada cliente." },
  { id: "descricao", title: "Registre cada visita", subtitle: "Descrição pronta e MEGA", icon: FileText, color: "bg-sky-50 text-sky-900", what: "Gere descrição da tarefa, objeções, próximos passos e abordagem baseada no MEGA.", how: "Preencha cliente, TPV, concorrente, share, condições e próxima visita; copie o resultado.", impact: "Seu histórico fica claro, acionável e útil para a próxima conversa." },
  { id: "reunioes", title: "Acompanhe reuniões", subtitle: "Uma agenda compartilhada", icon: CalendarDays, color: "bg-violet-50 text-violet-900", what: "Registre reuniões novas, importe clientes da Estratégia e acompanhe status, rota e retorno.", how: "Use Importar da estratégia, selecione os clientes e atualize o resultado da reunião.", impact: "Menos oportunidades esquecidas e mais continuidade entre pessoas e etapas." },
  { id: "rmr", title: "Meça e corrija", subtitle: "RMR com ação concreta", icon: BarChart3, color: "bg-orange-50 text-orange-900", what: "Veja indicadores do período, causas, plano de ação, responsável, prazo e resultado esperado.", how: "Revise os números automáticos, edite quando necessário e registre a ação que corrige o desvio.", impact: "Você aprende com o mês e evita repetir o mesmo problema." },
  { id: "spartacus", title: "Evolua com SPARTACUS", subtitle: "Desenvolvimento contínuo", icon: SpartacusEmblem, color: "bg-rose-50 text-rose-900", what: "Escolha hard e soft skills e gere um PDI com missões semanais e prática deliberada.", how: "Selecione competências, defina objetivo e reserve blocos curtos para praticar.", impact: "Resultado comercial e desenvolvimento pessoal passam a caminhar juntos." },
  { id: "final", title: "Feche o ciclo", subtitle: "Card, ranking e aprendizado", icon: Flag, color: "bg-yellow-50 text-yellow-900", what: "Registre o resultado final, acompanhe histórico e reconheça evolução no ranking.", how: "Compare objetivo e realizado, registre o card e use o histórico para planejar a próxima fase.", impact: "A jornada deixa de ser uma sequência de tarefas e vira aprendizado acumulado." },
];

export default function PlatformTutorialPanel() {
  const [activeId, setActiveId] = useState("painel");
  const active = steps.find(step => step.id === activeId) ?? steps[0];
  const ActiveIcon = active.icon;
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-2xl bg-[#002b1d] p-6 text-white md:p-8">
      <div className="absolute -right-12 -top-12 h-48 w-48 rounded-full border border-[#d4af37]/40 shadow-[0_0_0_24px_rgba(0,212,126,.08)]" />
      <div className="relative flex flex-col items-start gap-4 md:flex-row md:items-center"><ItakaEmblem size={68} /><div><p className="font-mono text-[10px] font-semibold tracking-[.18em] text-[#8fe6bd]">TUTORIAL NOVA ODISSEIA 2.0</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.055em] md:text-4xl">Sua travessia, passo a passo.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-100/75">Aprenda o que cada módulo faz, como usar e qual impacto ele pode gerar na sua rotina como agente.</p></div></div>
      <div className="mt-6 flex items-center gap-2 text-xs font-semibold text-[#d4af37]"><PlayCircle size={17} /> PLANEJAR → EXECUTAR → MEDIR → CORRIGIR → EVOLUIR</div>
    </section>
    <section className="rounded-xl border border-emerald-100 bg-white p-5">
      <div className="mb-5 flex items-center gap-2"><BookOpen className="text-emerald-600" size={18} /><div><p className="font-mono text-[10px] tracking-[.14em] text-emerald-600">MAPA DA PLATAFORMA</p><h3 className="mt-1 text-xl font-semibold">Escolha uma etapa para aprender.</h3></div></div>
      <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-5">{steps.map(step => { const Icon = step.icon; return <Button key={step.id} variant="outline" className={`h-auto min-h-28 justify-start whitespace-normal border-emerald-100 p-4 text-left ${activeId === step.id ? "border-[#00d47e] bg-emerald-50" : "bg-white"}`} onClick={() => setActiveId(step.id)}><span className={`mr-3 grid h-9 w-9 shrink-0 place-items-center rounded-lg ${step.color}`}><Icon size={20} /></span><span><b className="block text-sm text-emerald-950">{step.title}</b><small className="mt-1 block text-xs font-normal text-emerald-700/65">{step.subtitle}</small></span></Button>; })}</div>
    </section>
    <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]">
      <article className={`rounded-xl p-6 ${active.color}`}><ActiveIcon size={34} /><p className="mt-5 font-mono text-[10px] font-semibold tracking-[.14em]">ETAPA SELECIONADA</p><h3 className="mt-2 text-2xl font-semibold">{active.title}</h3><p className="mt-2 text-sm opacity-75">{active.subtitle}</p></article>
      <article className="rounded-xl border border-emerald-100 bg-white p-6"><div className="grid gap-5"><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-600">O QUE É POSSÍVEL FAZER</p><p className="mt-2 text-sm leading-6 text-emerald-950">{active.what}</p></div><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-600">COMO USAR</p><p className="mt-2 text-sm leading-6 text-emerald-950">{active.how}</p></div><div className="rounded-lg bg-[#f6f8f2] p-4"><p className="font-mono text-[10px] tracking-[.12em] text-emerald-600">IMPACTO POSITIVO NA VIDA DO AGENTE</p><p className="mt-2 text-sm font-semibold leading-6 text-emerald-950">{active.impact}</p></div></div></article>
    </section>
    <section className="grid gap-3 sm:grid-cols-3"><article className="rounded-xl border border-emerald-100 bg-white p-5"><Compass className="text-emerald-600" size={22} /><b className="mt-3 block">Mais direção</b><p className="mt-1 text-xs leading-5 text-emerald-700/65">Saiba o próximo passo antes de terminar a visita ou o dia.</p></article><article className="rounded-xl border border-emerald-100 bg-white p-5"><SearchCheck className="text-emerald-600" size={22} /><b className="mt-3 block">Mais preparo</b><p className="mt-1 text-xs leading-5 text-emerald-700/65">Use dados reais para conversar melhor e decidir com menos achismo.</p></article><article className="rounded-xl border border-emerald-100 bg-white p-5"><Sparkles className="text-emerald-600" size={22} /><b className="mt-3 block">Mais evolução</b><p className="mt-1 text-xs leading-5 text-emerald-700/65">Transforme histórico em aprendizado e aprendizado em performance.</p></article></section>
  </div>;
}
