import { Button } from "@/components/ui/button";
import { Bell, BookOpen, CheckCircle2, ChevronRight, FileDown } from "lucide-react";
import { exportPrivatePdf } from "@/lib/printDocument";
import { trpc } from "../lib/trpc";

export default function SkillsDashboard({ onOpenSpartacus }: { onOpenSpartacus: () => void }) {
  const utils = trpc.useUtils();
  const progress = trpc.spartacus.progress.useQuery();
  const notifications = trpc.notifications.list.useQuery();
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate() });
  const updateProgress = trpc.spartacus.updateProgress.useMutation({ onSuccess: () => utils.spartacus.progress.invalidate() });
  const unread = notifications.data?.filter(item => !item.readAt).length ?? 0;
  const summary = progress.data;
  const exportPdi = () => { const plan = summary?.plan; if (!plan) return; const ok = exportPrivatePdf("PDI SPARTACUS", plan.goal ?? "Plano individual de desenvolvimento", [{ title: "Competências escolhidas", items: [...(plan.hardSkills ?? []), ...(plan.softSkills ?? [])].map((skill: { title: string; category: string }) => `${skill.title} (${skill.category === "hard" ? "hard skill" : "soft skill"})`) }, ...(plan.weeklyMissions ?? []).map((week: { week: number; title: string; objective: string; sessions: string[] }) => ({ title: `Semana ${week.week} — ${week.title}`, text: week.objective, items: week.sessions })), { title: "Referências", items: (plan.references ?? []).map((reference: { label: string; url: string }) => `${reference.label}: ${reference.url}`) }]); if (!ok) window.alert("Permita a abertura da janela de impressão para salvar o PDF."); };
  return <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]">
    <article className="rounded-xl border border-emerald-100 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] font-semibold tracking-[.12em] text-emerald-600">DESENVOLVIMENTO SPARTACUS</p><h3 className="mt-1 text-xl font-semibold">Progresso das skills escolhidas</h3><p className="mt-1 text-sm text-emerald-800/65">Registre práticas reais em etapas de 25%; nenhum avanço é estimado pela plataforma.</p></div>{summary?.pdiId ? <div className="grid h-16 w-16 place-items-center rounded-full text-sm font-bold text-emerald-950" style={{ background: `conic-gradient(#b7ed4a ${summary.overallProgress * 3.6}deg, #e6f1e9 0deg)` }}><span className="grid h-12 w-12 place-items-center rounded-full bg-white">{summary.overallProgress}%</span></div> : null}</div>{summary?.pdiId ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{summary.skills.map(skill => <button type="button" key={skill.id} disabled={updateProgress.isPending} onClick={() => updateProgress.mutate({ pdiId: summary.pdiId!, skillId: skill.id, progressPercent: Math.min(100, skill.progressPercent + 25) })} className="rounded-lg p-1 text-left transition hover:bg-lime-50 disabled:opacity-60"><div className="flex justify-between gap-3 text-xs"><span className="truncate font-medium">{skill.title}</span><b>{skill.progressPercent}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-emerald-50"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${skill.progressPercent}%` }} /></div><small className="mt-1 block text-[10px] text-emerald-700/60">Toque para registrar prática</small></button>)}</div> : <div className="mt-5 rounded-lg bg-[#f5f8f2] p-4 text-sm text-emerald-800/70">Gere um PDI para iniciar um acompanhamento de seis competências.</div>}<div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" className="border-emerald-200 text-emerald-900" onClick={onOpenSpartacus}><BookOpen size={16} /> {summary?.pdiId ? "Ver meu PDI" : "Criar meu PDI"}<ChevronRight size={15} /></Button>{summary?.pdiId && <Button variant="outline" className="border-emerald-200 text-emerald-900" onClick={exportPdi}><FileDown size={16} /> Exportar PDI em PDF</Button>}</div></article>
    <article className="rounded-xl border border-emerald-100 bg-white p-5"><div className="flex items-start justify-between gap-3"><span className="relative grid h-10 w-10 place-items-center rounded-lg bg-lime-100 text-emerald-800"><Bell size={19} />{unread > 0 && <b className="absolute -right-2 -top-2 grid h-5 min-w-5 place-items-center rounded-full bg-emerald-700 px-1 text-[10px] text-white">{unread}</b>}</span><div><p className="font-mono text-[10px] font-semibold tracking-[.12em] text-emerald-600">NOTIFICAÇÕES</p><h3 className="mt-1 text-xl font-semibold">Seu centro privado</h3></div></div><div className="mt-4 space-y-2">{notifications.data?.slice(0, 3).map(item => <button type="button" key={item.id} onClick={() => !item.readAt && markRead.mutate({ id: item.id })} className={`w-full rounded-lg p-3 text-left text-xs ${item.readAt ? "bg-[#f5f8f2] text-emerald-800/70" : "bg-lime-50 text-emerald-950"}`}><div className="flex items-center justify-between gap-3"><b>{item.title}</b>{!item.readAt && <CheckCircle2 size={14} className="text-emerald-600" />}</div><p className="mt-1 leading-5">{item.body}</p></button>)}{!notifications.isLoading && !notifications.data?.length && <p className="rounded-lg bg-[#f5f8f2] p-4 text-sm text-emerald-800/65">Quando um PDI for gerado, o aviso aparecerá aqui.</p>}</div></article>
  </section>;
}
