import { BellRing, BookOpen, CheckCircle2, Compass, Flag, Map, Sparkles } from "lucide-react";

type Destination = "jornada" | "arauto" | "historia";
const steps = [
  { number: "01", title: "Encontre seu norte", body: "Abra Minha Jornada, escreva seu Chamado e escolha a transformação que guiará os próximos 30 dias.", icon: Compass, destination: "jornada" as Destination, action: "Abrir Minha Jornada" },
  { number: "02", title: "Leia o seu mapa", body: "Ajuste as quatro áreas da Vida 360. Elas mostram onde há força e onde sua atenção faz diferença agora.", icon: Map, destination: "jornada" as Destination, action: "Revisar Vida 360" },
  { number: "03", title: "Atravesse um dia", body: "Cumpra uma missão e faça seu check-in. Energia, percepção e próxima ação ficam no Diário de Bordo.", icon: CheckCircle2, destination: "jornada" as Destination, action: "Fazer check-in" },
  { number: "04", title: "Entenda o capítulo", body: "Visite História para descobrir como sua etapa conversa com os movimentos da Odisseia de Homero.", icon: BookOpen, destination: "historia" as Destination, action: "Navegar pela História" },
];

export default function StartHerePanel({ onNavigate }: { onNavigate: (view: Destination) => void }) {
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl bg-[#082f27] p-7 text-white shadow-xl md:p-10"><div className="absolute -right-16 -top-16 h-64 w-64 rounded-full border-[36px] border-amber-200/10"/><div className="absolute bottom-6 right-10 hidden text-amber-200/20 md:block"><Compass size={170} strokeWidth={.7}/></div><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-amber-200/25 bg-white/5 px-3 py-1 font-mono text-[10px] tracking-[.14em] text-amber-200"><Sparkles size={13}/> COMECE POR AQUI</span><h2 className="mt-5 text-4xl font-semibold tracking-[-.06em] md:text-5xl">Sua vida é a jornada.<br/>A plataforma é o mapa.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-emerald-100/75">Em poucos minutos você encontra seu norte, registra o momento atual e escolhe uma ação possível. Não precisa preencher tudo de uma vez.</p><button onClick={()=>onNavigate("jornada")} className="mt-6 rounded-xl bg-amber-200 px-5 py-3 text-sm font-semibold text-emerald-950 transition hover:-translate-y-0.5 hover:bg-amber-100">Começar minha travessia</button></div></section>
    <section><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-600">ROTA INICIAL</p><h3 className="mt-1 text-2xl font-semibold">Quatro passos. Um ciclo que se repete.</h3></div><Flag className="text-amber-600"/></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{steps.map(({number,title,body,icon:Icon,destination,action})=><article key={number} className="group rounded-2xl border border-emerald-100 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-amber-300 hover:shadow-lg"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon/></span><span className="font-mono text-5xl text-emerald-100 transition group-hover:text-amber-100">{number}</span></div><h4 className="mt-4 text-xl font-semibold">{title}</h4><p className="mt-2 text-sm leading-6 text-emerald-900/60">{body}</p><button onClick={()=>onNavigate(destination)} className="mt-4 text-sm font-semibold text-emerald-700 hover:text-amber-700">{action} →</button></article>)}</div></section>
    <section className="grid gap-4 md:grid-cols-2"><button onClick={()=>onNavigate("arauto")} className="flex items-center gap-4 rounded-2xl bg-[#542704] p-5 text-left text-amber-50 transition hover:-translate-y-1"><span className="grid h-11 w-11 place-items-center rounded-full bg-amber-200 text-amber-950"><BellRing/></span><span><b className="block">O que mudou?</b><small className="text-amber-100/70">O Arauto anuncia cada novidade da plataforma.</small></span></button><div className="rounded-2xl border border-lime-300 bg-lime-50 p-5"><b>Ritmo recomendado</b><p className="mt-1 text-sm text-emerald-900/65">Um check-in por dia e uma revisão da rota por semana. Profundidade vem da constância.</p></div></section>
  </div>;
}
