import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Filter, Flame, Layers3, Search, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
const percent = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 });

function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) {
  return <label className="grid gap-1 text-[11px] font-medium text-emerald-800"><span>{label}</span><select className="h-9 rounded-md border border-emerald-100 bg-white px-2 text-xs text-emerald-950" value={value} onChange={event => onChange(event.target.value)}><option value="">Todos</option>{options.map(option => <option key={option} value={option}>{option}</option>)}</select></label>;
}

export default function SuperPipePanel() {
  const [monthKey, setMonthKey] = useState(""); const [query, setQuery] = useState(""); const [polo, setPolo] = useState(""); const [agent, setAgent] = useState("");
  const filters = useMemo(() => ({ ...(monthKey ? { monthKey } : {}), ...(query ? { query } : {}), ...(polo ? { polo } : {}), ...(agent ? { agent } : {}) }), [agent, monthKey, polo, query]);
  const pipeline = trpc.leadership.salesPipeline.useQuery(filters);
  const data = pipeline.data; const options = data?.filterOptions;
  return <div className="space-y-6"><section className="leader-command-hero ledger-surface rounded-lg border border-emerald-100 bg-white p-6 md:p-8"><p className="ledger-index font-mono text-[10px] font-semibold tracking-[.14em] text-emerald-600">SUPER PIPE / FUNIL DO POLO</p><div className="mt-3 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h2 className="text-3xl font-semibold tracking-[-.055em]">Prioridade no que pode avançar a rota.</h2><p className="mt-2 max-w-2xl text-sm text-emerald-800/65">O painel consolida somente dados reais do Funil do Pipe em rotas formalmente atribuídas ao escopo da liderança. Não há métricas pessoais de RV nesta visão.</p></div><div className="rounded-md bg-lime-100 px-4 py-3 text-xs text-emerald-950"><b>{data?.summary.totalOpportunities ?? 0}</b> oportunidades · <b>{brl.format(data?.summary.projectedTpv ?? 0)}</b> em TPV projetado</div></div></section>
    <section className="rounded-xl border border-emerald-100 bg-white p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="grid gap-1 text-[11px] font-medium text-emerald-800"><span>Competência</span><Input type="month" value={monthKey} onChange={event => setMonthKey(event.target.value)} /></label><label className="relative grid gap-1 text-[11px] font-medium text-emerald-800"><span>Buscar</span><Search className="pointer-events-none absolute bottom-2.5 left-3 text-emerald-500" size={15} /><Input className="pl-8" value={query} onChange={event => setQuery(event.target.value)} placeholder="Cliente, rota ou segmento" /></label><SelectField label="Polo" value={polo} onChange={setPolo} options={options?.polos ?? []} /><SelectField label="Agente responsável" value={agent} onChange={setAgent} options={options?.agents ?? []} /></div><div className="mt-3 flex items-center gap-2 text-xs text-emerald-700/65"><Filter size={14} /> Filtros aplicados ao escopo organizacional liberado para sua conta.</div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data?.superPipe.map(stage => <article key={stage.key} className={`rounded-xl border p-4 ${stage.key === "negotiation" ? "border-lime-300 bg-lime-100" : stage.key === "lost" ? "border-rose-100 bg-rose-50" : "border-emerald-100 bg-white"}`}><p className="font-mono text-[10px] tracking-[.1em] text-emerald-700/65">{stage.shortLabel.toUpperCase()}</p><strong className="mt-2 block text-2xl tracking-tight">{stage.count}</strong><span className="mt-1 block text-xs text-emerald-800/65">{brl.format(stage.projectedTpv)} projetado</span></article>) ?? Array.from({ length: 6 }).map((_, index) => <article className="h-24 animate-pulse rounded-xl border border-emerald-100 bg-white" key={index} />)}</section>
    <section className="grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><article className="rounded-xl border border-emerald-100 bg-white p-5"><div className="flex items-center gap-2"><TrendingUp className="text-emerald-600" size={18} /><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-600">CONVERSÃO</p><h3 className="font-semibold">Fluxo entre etapas.</h3></div></div><div className="mt-5 space-y-3">{data?.conversion.map(item => <div className="rounded-lg bg-[#f6f8f2] p-3" key={`${item.from}-${item.to}`}><div className="flex justify-between gap-3 text-xs"><span>{item.from} <span className="text-emerald-600">→</span> {item.to}</span><b>{percent.format(item.rate)}%</b></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-emerald-100"><div className="h-full rounded-full bg-lime-400" style={{ width: `${Math.min(item.rate, 100)}%` }} /></div></div>) ?? <p className="text-sm text-emerald-700/60">Carregando conversões...</p>}</div></article>
      <article className="rounded-xl border border-emerald-100 bg-white p-5"><div className="flex items-center gap-2"><Flame className="text-amber-500" size={18} /><div><p className="font-mono text-[10px] tracking-[.12em] text-emerald-600">OPORTUNIDADES QUENTES</p><h3 className="font-semibold">Prioridade de ação.</h3></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-xs"><thead className="border-b border-emerald-100 font-mono text-[10px] uppercase tracking-[.08em] text-emerald-700/65"><tr><th className="pb-3">Cliente / rota</th><th className="pb-3">Responsável</th><th className="pb-3">Etapa</th><th className="pb-3">TPV</th><th className="pb-3">Próxima ação</th></tr></thead><tbody>{data?.hotOpportunities.map(item => <tr className="border-b border-emerald-50" key={item.id}><td className="py-3"><b>{item.clientName}</b><small className="block text-emerald-700/60">{item.route} · {item.city || "Cidade não informada"}</small></td><td className="py-3">{item.agent || "Aguardando responsável"}</td><td className="py-3"><span className="rounded bg-amber-50 px-2 py-1 text-amber-900">{item.superStage}</span></td><td className="py-3 font-mono">{brl.format(item.projectedTpv)}</td><td className="py-3 text-emerald-700/70"><b className="block font-medium text-emerald-900">{item.nextAction || "Não definida"}</b><small>{item.nextContactAt ? new Date(item.nextContactAt).toLocaleDateString("pt-BR") : item.lastInteraction || "Sem data de contato"}</small></td></tr>)}{!pipeline.isLoading && !data?.hotOpportunities.length && <tr><td colSpan={5} className="py-7 text-center text-emerald-700/65"><Layers3 className="mx-auto mb-2 text-emerald-300" size={22} />Não há oportunidades quentes nas rotas e filtros selecionados.</td></tr>}</tbody></table></div></article></section>
  </div>;
}
