import { ArrowRight, BookOpenCheck, Brain, CheckCircle2, Flame, Footprints, Mountain, ShieldCheck, Sparkles, Target } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Destination = "jornada" | "historia";
type Mission = { id:string; title:string; done:boolean; xp:number };
type Journey = { calling?:string; cycleGoal?:string; stage?:"Chamado"|"Provação"|"Maestria"|"Retorno"; xp?:number; streak?:number; missions?:Mission[]; checkins?:{date:string; energy?:number; reflection?:string; nextAction?:string}[] };

export default function UlissesPanel({ onNavigate }: { onNavigate:(view:Destination)=>void }) {
  const journey = trpc.agent.journey.useQuery();
  const state = (journey.data?.state || {}) as Journey;
  const missions = state.missions || [];
  const pending = missions.filter(item=>!item.done);
  const completed = missions.length - pending.length;
  const progress = missions.length ? Math.round(completed / missions.length * 100) : 0;
  const latest = state.checkins?.[0];
  const activeTrial = pending[0];
  const stageReady = state.stage === "Provação" || state.stage === "Maestria" || state.stage === "Retorno";
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl border border-amber-200/20 bg-[#3a1d16] p-7 text-white shadow-xl md:p-10"><div className="absolute inset-x-0 top-0 h-2 bg-[repeating-linear-gradient(90deg,#f6d77a_0_14px,transparent_14px_22px,#f6d77a_22px_28px,transparent_28px_36px)] opacity-45"/><div className="absolute -right-20 -top-24 h-80 w-80 rounded-full border-[42px] border-orange-200/10"/><div className="absolute right-14 top-12 hidden h-24 w-24 place-items-center rounded-full border-2 border-amber-200/25 bg-amber-100/5 text-center font-serif text-5xl text-amber-100/25 md:grid">Ω</div><Mountain className="absolute bottom-6 right-10 hidden text-orange-100/10 md:block" size={180} strokeWidth={.7}/><div className="relative max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-orange-100/25 bg-white/5 px-3 py-1 font-mono text-[10px] tracking-[.15em] text-orange-100"><Footprints size={13}/> PORTAL ULISSES</span><h2 className="mt-5 text-4xl font-semibold tracking-[-.06em] md:text-5xl">Coragem não é ausência de medo.<br/>É movimento com sentido.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-orange-50/70">Transforme a grande travessia em provas possíveis. Ulisses protege sua intenção, mostra o obstáculo atual e pede uma evidência concreta de avanço.</p><div className="mt-6 flex flex-wrap gap-2"><span className="rounded-full border border-amber-100/20 bg-amber-50/10 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">MÉTIS · ASTÚCIA</span><span className="rounded-full border border-amber-100/20 bg-amber-50/10 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">THYMÓS · CORAGEM</span><span className="rounded-full border border-amber-100/20 bg-amber-50/10 px-3 py-1 text-[10px] tracking-[.12em] text-amber-100">NÓSTOS · RETORNO</span></div></div></section>

    <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]"><article className="rounded-2xl border border-orange-100 bg-white p-6"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] tracking-[.12em] text-orange-700">PROVA ATUAL</p><h3 className="mt-1 text-2xl font-semibold">{activeTrial?.title || "Escolha a primeira prova da travessia"}</h3></div><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-orange-100 text-orange-800"><Flame/></span></div><p className="mt-4 text-sm leading-7 text-emerald-950/65">{activeTrial ? `Vale ${activeTrial.xp} XP. Faça o menor gesto que deixa uma evidência visível ainda hoje.` : "Crie uma missão em Minha Jornada. Uma boa prova é pequena o bastante para começar e importante o bastante para mudar sua direção."}</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-orange-50 px-3 py-1 text-xs text-orange-800">1 ação observável</span><span className="rounded-full bg-orange-50 px-3 py-1 text-xs text-orange-800">até o fim do dia</span><span className="rounded-full bg-orange-50 px-3 py-1 text-xs text-orange-800">registro no diário</span></div><button onClick={()=>onNavigate("jornada")} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-orange-800">{activeTrial ? "Abrir missão" : "Criar minha prova"}<ArrowRight size={16}/></button></article>
    <article className="rounded-2xl bg-[#173c32] p-6 text-white"><p className="font-mono text-[10px] tracking-[.12em] text-lime-200">ESCUDO DE INTENÇÃO</p><ShieldCheck className="mt-4 text-lime-200" size={34}/><p className="mt-4 text-xs uppercase tracking-[.12em] text-emerald-100/55">Por que atravessar?</p><b className="mt-2 block text-xl leading-7">{state.calling || "Dê nome ao seu Chamado para lembrar por que esta prova importa."}</b><p className="mt-5 text-sm leading-6 text-emerald-50/65">{state.cycleGoal ? `Meta do ciclo: ${state.cycleGoal}` : "Sua meta de 30 dias funciona como critério para dizer sim ou não ao que aparece no caminho."}</p></article></section>

    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-orange-100 bg-white p-5"><Target className="text-orange-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-orange-700">PROVAS CONCLUÍDAS</p><b className="mt-1 block text-3xl">{completed}/{missions.length}</b><div className="mt-3 h-2 overflow-hidden rounded-full bg-orange-50"><div className="h-full rounded-full bg-orange-500" style={{width:`${progress}%`}}/></div><p className="mt-2 text-xs text-emerald-900/55">{progress}% da travessia atual</p></article><article className="rounded-2xl border border-amber-100 bg-white p-5"><Sparkles className="text-amber-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-amber-700">CORAGEM ACUMULADA</p><b className="mt-1 block text-3xl">{state.xp || 0} XP</b><p className="mt-2 text-sm text-emerald-900/60">experiência convertida em repertório</p></article><article className="rounded-2xl border border-emerald-100 bg-white p-5"><CheckCircle2 className="text-emerald-700"/><p className="mt-4 font-mono text-[10px] tracking-[.1em] text-emerald-700">RITMO PROTEGIDO</p><b className="mt-1 block text-3xl">{state.streak || 0} dia(s)</b><p className="mt-2 text-sm text-emerald-900/60">de retorno consciente à jornada</p></article></section>

    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-emerald-100 bg-white p-6"><div className="flex items-center gap-3"><Brain className="text-emerald-700"/><div><p className="font-mono text-[10px] tracking-[.1em] text-emerald-700">DEPOIS DA PROVA</p><h3 className="text-xl font-semibold">Converter experiência em aprendizado</h3></div></div><div className="mt-5 grid gap-3 text-sm"><div className="rounded-xl bg-[#f4f3ec] p-4"><b>1. O que aconteceu?</b><p className="mt-1 text-emerald-900/60">Registre fatos, sem julgamento.</p></div><div className="rounded-xl bg-[#f4f3ec] p-4"><b>2. O que isso revela?</b><p className="mt-1 text-emerald-900/60">Nomeie padrão, força ou limite.</p></div><div className="rounded-xl bg-[#f4f3ec] p-4"><b>3. Qual é o próximo gesto?</b><p className="mt-1 text-emerald-900/60">Ajuste a rota com uma ação pequena.</p></div></div><button onClick={()=>onNavigate("jornada")} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-emerald-800"><BookOpenCheck size={16}/> Registrar no Diário de Bordo</button></article><article className="rounded-2xl border border-sky-100 bg-sky-50 p-6"><p className="font-mono text-[10px] tracking-[.12em] text-sky-800">LEITURA DO MOMENTO</p><h3 className="mt-2 text-xl font-semibold">{stageReady ? "Você já entrou na travessia." : "Você está preparando a partida."}</h3><p className="mt-3 text-sm leading-7 text-emerald-950/65">{latest?.reflection ? `Última evidência: ${latest.reflection}` : "Ainda não há uma evidência registrada. O primeiro check-in não precisa ser perfeito: basta dizer o que você tentou e o que percebeu."}</p>{latest?.nextAction && <div className="mt-4 rounded-xl bg-white p-4"><small className="font-mono text-[9px] tracking-[.1em] text-sky-700">PRÓXIMA AÇÃO DECLARADA</small><b className="mt-2 block">{latest.nextAction}</b></div>}<button onClick={()=>onNavigate("historia")} className="mt-5 text-sm font-semibold text-sky-800">Entender Ulisses na sua História →</button></article></section>
  </div>;
}
