import { buildNordicScore } from "./nordic";

export const SUPER_PIPE_STAGES = [
  { key: "planned", label: "Novos planejados", shortLabel: "Planejados", description: "Clientes na aba de novos planejados." },
  { key: "qualification", label: "Novos em qualificação", shortLabel: "Qualificação", description: "Clientes em descoberta e validação." },
  { key: "negotiation", label: "Novos em negociação", shortLabel: "Negociação", description: "Clientes com proposta ou negociação em curso." },
  { key: "lost", label: "Novos perdidos", shortLabel: "Perdidos", description: "Clientes encerrados sem avanço." },
  { key: "customer", label: "Novos clientes", shortLabel: "Clientes", description: "Clientes conquistados no período." },
  { key: "active", label: "Novos ativos", shortLabel: "Ativos", description: "Clientes novos já ativados." },
] as const;
export const POLO_FUNNEL_STAGES = [
  { key: "qualification", label: "Qualificações", description: "Planejados e clientes em qualificação." },
  { key: "proposals", label: "Propostas", description: "Negociações e propostas em andamento." },
  { key: "customer", label: "Novos clientes", description: "Clientes conquistados." },
  { key: "active", label: "Novos ativos", description: "Clientes novos com ativação concluída." },
] as const;
export type SuperPipeStage = (typeof SUPER_PIPE_STAGES)[number]["key"];
export type PoloFunnelStage = (typeof POLO_FUNNEL_STAGES)[number]["key"];
export type SalesPipeEntry = { id: number; date: string; subchannel: string; ownHub: string; regional: string; district: string; polo: string; agent: string; activeTeam: string; effectiveTeam: string; route: string; clientName: string; document: string; segment: string; mcc: string; projectedTpv: number; sourceStage: string; temperature: string; city?: string; lastInteraction?: string; nextAction?: string; nextContactAt?: Date | null; notes?: string | null; };
export type SalesPipeFilters = { monthKey?: string; query?: string; subchannel?: string; ownHub?: string; regional?: string; district?: string; polo?: string; agent?: string; activeTeam?: string; effectiveTeam?: string; };

export function normalizeSalesPipeValue(value: string | null | undefined) { return (value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR").trim().replace(/\s+/g, " "); }
export function getSuperPipeStage(value: string | null | undefined): SuperPipeStage { const stage = normalizeSalesPipeValue(value); if (stage.includes("perdid") || stage.includes("lost") || stage.includes("cancel")) return "lost"; if (stage.includes("ativ")) return "active"; if (stage.includes("cliente") || stage.includes("ganho") || stage.includes("fechado") || stage.includes("concluid")) return "customer"; if (stage.includes("negoci") || stage.includes("propost")) return "negotiation"; if (stage.includes("qualific")) return "qualification"; return "planned"; }
export function getPoloFunnelStage(value: string | null | undefined): PoloFunnelStage | null { const stage = getSuperPipeStage(value); if (stage === "planned" || stage === "qualification") return "qualification"; if (stage === "negotiation") return "proposals"; if (stage === "customer") return "customer"; if (stage === "active") return "active"; return null; }
export function isHotOpportunity(value: string | null | undefined) { const temperature = normalizeSalesPipeValue(value); return temperature.includes("quente") || temperature.includes("hot") || temperature.includes("alta"); }
export function toSalesPipeMonthKey(value: string | null | undefined) { const raw = (value ?? "").trim(); const iso = raw.match(/^(\d{4})[-/](\d{1,2})/); if (iso) return `${iso[1]}-${iso[2].padStart(2, "0")}`; const brazilian = raw.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})/); return brazilian ? `${brazilian[3]}-${brazilian[2].padStart(2, "0")}` : ""; }
function selected(value: string, filter?: string) { return !filter || filter === "all" || normalizeSalesPipeValue(value) === normalizeSalesPipeValue(filter); }
export function filterSalesPipeEntries(entries: SalesPipeEntry[], filters: SalesPipeFilters = {}) { const query = normalizeSalesPipeValue(filters.query); return entries.filter(entry => { const searchable = [entry.clientName, entry.agent, entry.route, entry.polo, entry.segment, entry.document].join(" "); return (!filters.monthKey || toSalesPipeMonthKey(entry.date) === filters.monthKey) && (!query || normalizeSalesPipeValue(searchable).includes(query)) && selected(entry.subchannel, filters.subchannel) && selected(entry.ownHub, filters.ownHub) && selected(entry.regional, filters.regional) && selected(entry.district, filters.district) && selected(entry.polo, filters.polo) && selected(entry.agent, filters.agent) && selected(entry.activeTeam, filters.activeTeam) && selected(entry.effectiveTeam, filters.effectiveTeam); }); }
const sumTpv = (entries: SalesPipeEntry[]) => entries.reduce((sum, entry) => sum + Math.max(entry.projectedTpv, 0), 0);
function priority(entry: SalesPipeEntry) { const stage = getSuperPipeStage(entry.sourceStage); const bonus = stage === "negotiation" ? 250_000 : stage === "qualification" ? 125_000 : stage === "planned" ? 50_000 : 0; return buildNordicScore({ temperature: isHotOpportunity(entry.temperature) ? "quente" : "frio", projectedTpv: entry.projectedTpv, nextContactAt: entry.nextContactAt }) + bonus; }
export function calculateSalesPipeline(entries: SalesPipeEntry[], filters: SalesPipeFilters = {}) { const filtered = filterSalesPipeEntries(entries, filters); const superPipe = SUPER_PIPE_STAGES.map(stage => { const rows = filtered.filter(entry => getSuperPipeStage(entry.sourceStage) === stage.key); return { ...stage, count: rows.length, projectedTpv: sumTpv(rows) }; }); const poloFunnel = POLO_FUNNEL_STAGES.map(stage => { const rows = filtered.filter(entry => getPoloFunnelStage(entry.sourceStage) === stage.key); return { ...stage, count: rows.length, projectedTpv: sumTpv(rows) }; }); const count = (stage: SuperPipeStage) => superPipe.find(item => item.key === stage)?.count ?? 0; const conversion = [["Novos planejados", "Em qualificação", "planned", "qualification"], ["Em qualificação", "Em negociação", "qualification", "negotiation"], ["Em negociação", "Novos clientes", "negotiation", "customer"], ["Novos clientes", "Novos ativos", "customer", "active"]].map(([from, to, origin, destination]) => ({ from, to, rate: count(origin as SuperPipeStage) ? count(destination as SuperPipeStage) / count(origin as SuperPipeStage) * 100 : 0 })); const hotOpportunities = [...filtered].filter(entry => !["lost", "active"].includes(getSuperPipeStage(entry.sourceStage))).sort((a, b) => priority(b) - priority(a)).slice(0, 12).map(entry => ({ ...entry, priorityScore: priority(entry), superStage: getSuperPipeStage(entry.sourceStage) })); return { entries: filtered, superPipe, poloFunnel, conversion, hotOpportunities, summary: { totalOpportunities: filtered.length, projectedTpv: sumTpv(filtered), hotOpportunities: filtered.filter(entry => isHotOpportunity(entry.temperature)).length, proposalTpv: sumTpv(filtered.filter(entry => getSuperPipeStage(entry.sourceStage) === "negotiation")) } }; }
export function listSalesPipeFilterOptions(entries: SalesPipeEntry[]) { const unique = (selector: (entry: SalesPipeEntry) => string) => Array.from(new Set(entries.map(selector).filter(Boolean))).sort((a, b) => a.localeCompare(b, "pt-BR")); return { months: Array.from(new Set(entries.map(entry => toSalesPipeMonthKey(entry.date)).filter(Boolean))).sort().reverse(), subchannels: unique(entry => entry.subchannel), ownHubs: unique(entry => entry.ownHub), regionals: unique(entry => entry.regional), districts: unique(entry => entry.district), polos: unique(entry => entry.polo), agents: unique(entry => entry.agent), activeTeams: unique(entry => entry.activeTeam), effectiveTeams: unique(entry => entry.effectiveTeam) }; }
