export type SpartacusSkillCategory = "hard" | "soft";

export type SpartacusSkill = {
  id: string;
  category: SpartacusSkillCategory;
  title: string;
  summary: string;
  practice: string;
  reference: { label: string; url: string };
};

const salesforceSpin = { label: "Salesforce — SPIN Selling", url: "https://www.salesforce.com/blog/sales/spin-selling/" };
const salesforcePipeline = { label: "Salesforce — Gestão de pipeline", url: "https://www.salesforce.com/sales/pipeline/management/" };
const hubspotProspecting = { label: "HubSpot — Prospecção", url: "https://blog.hubspot.com/sales/prospecting" };
const hubspotClosing = { label: "HubSpot — Técnicas de fechamento", url: "https://blog.hubspot.com/sales/sales-closing-techniques-and-why-they-work" };
const cclSbi = { label: "CCL — Feedback SBI", url: "https://www.ccl.org/articles/leading-effectively-articles/closing-the-gap-between-intent-vs-impact-sbii/" };
const atlassianKanban = { label: "Atlassian — Kanban", url: "https://www.atlassian.com/agile/kanban" };
const atlassianEisenhower = { label: "Atlassian — Matriz de Eisenhower", url: "https://www.atlassian.com/work-management/project-management/eisenhower-matrix" };
const googleSheets = { label: "Google — Treinamento de Planilhas", url: "https://support.google.com/a/users/answer/9282959?hl=pt-BR" };
const planaltoClt = { label: "Planalto — Consolidação das Leis do Trabalho", url: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452.htm" };

export const SPARTACUS_SKILLS: SpartacusSkill[] = [
  { id: "closing-techniques", category: "hard", title: "Técnicas de fechamento", summary: "Aplicar descoberta consultiva, qualificação e próximo passo explícito sem pressão indevida.", practice: "Monte cinco perguntas SPIN e feche cada simulação com uma pergunta de avanço honesta.", reference: salesforceSpin },
  { id: "pipeline-crm", category: "hard", title: "Gestão de funil e pipeline (CRM)", summary: "Manter etapas, critérios de saída, próximos passos e dados do funil confiáveis.", practice: "Revise cinco oportunidades e registre estágio, evidência, risco e próximo passo com data.", reference: salesforcePipeline },
  { id: "pricing-margins", category: "hard", title: "Precificação e cálculo de margens", summary: "Comparar preço, custo, margem e impacto comercial com clareza.", practice: "Faça três cenários de preço e explique premissas, margem e limites de negociação.", reference: googleSheets },
  { id: "commercial-proposals", category: "hard", title: "Elaboração de propostas comerciais", summary: "Estruturar proposta a partir de problema, valor, escopo, evidências e próximo passo.", practice: "Reescreva uma proposta em uma página com problema do cliente, solução e CTA objetivo.", reference: hubspotClosing },
  { id: "conversion-analytics", category: "hard", title: "Análise de dados e métricas de conversão", summary: "Ler conversões por etapa e identificar o gargalo que merece intervenção.", practice: "Calcule a conversão de três etapas do funil e formule uma hipótese verificável para o menor índice.", reference: salesforcePipeline },
  { id: "product-portfolio", category: "hard", title: "Conhecimento de produto e portfólio", summary: "Traduzir recursos em benefícios e casos de uso aderentes à dor do cliente.", practice: "Escolha três itens do portfólio e associe benefício, evidência permitida e perfil de cliente.", reference: hubspotProspecting },
  { id: "prospecting", category: "hard", title: "Técnicas de prospecção", summary: "Priorizar contas, pesquisar contexto público e iniciar conversas relevantes.", practice: "Prepare três abordagens com contexto, hipótese de dor e pergunta inicial, sem contato automático.", reference: hubspotProspecting },
  { id: "kpi-management", category: "hard", title: "Gestão de indicadores de desempenho (KPIs)", summary: "Conectar atividade, conversão, TPV e resultado em uma rotina de gestão.", practice: "Defina um indicador de entrada, um de processo e um de resultado para a próxima semana.", reference: salesforcePipeline },
  { id: "resource-planning", category: "hard", title: "Planejamento de escala e recursos", summary: "Dimensionar capacidade, prioridades, responsáveis e restrições antes de executar.", practice: "Transforme uma meta em capacidade semanal, donos, riscos e plano de contingência.", reference: atlassianKanban },
  { id: "sbi-feedback", category: "hard", title: "Condução de feedback estruturado (SBI)", summary: "Dar feedback com situação, comportamento observado, impacto e abertura para escuta.", practice: "Escreva dois feedbacks usando SBI e uma pergunta final sobre intenção.", reference: cclSbi },
  { id: "pdi-writing", category: "hard", title: "Elaboração de PDI", summary: "Converter uma competência em objetivo, prática deliberada, evidência e revisão.", practice: "Defina uma meta de 30 dias com comportamento observável, rotina semanal e critério de evidência.", reference: cclSbi },
  { id: "recruitment-selection", category: "hard", title: "Recrutamento e seleção", summary: "Estruturar critérios de seleção, perguntas situacionais e comparação ética de candidatos.", practice: "Crie uma matriz de critérios e três perguntas comportamentais para uma vaga hipotética.", reference: cclSbi },
  { id: "formal-conflict", category: "hard", title: "Gestão de conflitos formais e processuais", summary: "Separar fatos, interesses, impacto e próximos passos em conversas difíceis.", practice: "Descreva um conflito fictício com fatos verificáveis, interesses e proposta de mediação.", reference: cclSbi },
  { id: "labor-law-basics", category: "hard", title: "Legislação trabalhista básica", summary: "Reconhecer quando consultar políticas internas, RH ou orientação jurídica qualificada.", practice: "Liste três situações de trabalho que exigem consulta responsável, sem emitir parecer jurídico.", reference: planaltoClt },
  { id: "project-management", category: "hard", title: "Gestão de projetos (ágeis e Kanban)", summary: "Visualizar trabalho, limitar tarefas em andamento e revisar o fluxo continuamente.", practice: "Crie um quadro com A fazer, Em andamento, Revisão e Concluído, com limite de duas tarefas ativas.", reference: atlassianKanban },
  { id: "productivity-tools", category: "hard", title: "Ferramentas de produtividade", summary: "Usar planilhas, automações permitidas e templates para reduzir trabalho repetitivo.", practice: "Crie uma planilha com validação, filtro e fórmula para acompanhar uma rotina semanal.", reference: googleSheets },
  { id: "reports-presentations", category: "hard", title: "Relatórios e apresentações", summary: "Organizar uma mensagem executiva com contexto, dado, interpretação e decisão solicitada.", practice: "Faça um resumo de uma página: objetivo, três indicadores, aprendizado e próxima decisão.", reference: googleSheets },
  { id: "time-prioritization", category: "hard", title: "Gestão do tempo e priorização", summary: "Distinguir importância e urgência para proteger blocos de trabalho de alto impacto.", practice: "Classifique dez tarefas na matriz de Eisenhower e bloqueie dois períodos para o quadrante importante.", reference: atlassianEisenhower },
  { id: "process-improvement", category: "hard", title: "Análise de processos e melhoria contínua (PDCA)", summary: "Testar melhorias pequenas com hipótese, medida, execução e revisão.", practice: "Escolha um gargalo, formule um PDCA de sete dias e defina a métrica de verificação.", reference: atlassianKanban },
  { id: "digital-tools", category: "hard", title: "Ferramentas digitais do setor", summary: "Aprender fluxos essenciais de aplicativos de gestão, CRMs e ERPs usados no trabalho.", practice: "Liste três fluxos recorrentes, o dado de entrada, a saída esperada e onde validar erros.", reference: googleSheets },
  { id: "active-listening", category: "soft", title: "Escuta ativa", summary: "Ouvir para compreender, confirmar entendimento e fazer perguntas de aprofundamento.", practice: "Em uma conversa, faça duas perguntas abertas e resuma a resposta antes de propor algo.", reference: salesforceSpin },
  { id: "commercial-empathy", category: "soft", title: "Empatia comercial", summary: "Compreender contexto, dor e objetivo do cliente sem presumir necessidades.", practice: "Escreva a hipótese de dor de três perfis e uma pergunta de validação para cada um.", reference: hubspotProspecting },
  { id: "rejection-resilience", category: "soft", title: "Resiliência à rejeição", summary: "Tratar negativas como informação, proteger energia e retomar a cadência com ética.", practice: "Após três negativas simuladas, registre aprendizado, próximo teste e uma ação sob seu controle.", reference: hubspotProspecting },
  { id: "persuasion-argumentation", category: "soft", title: "Persuasão e argumentação", summary: "Defender uma recomendação com contexto, evidência, benefício e espaço para objeções.", practice: "Apresente uma recomendação em 60 segundos e responda a duas objeções sem inventar dados.", reference: hubspotClosing },
  { id: "customer-profile-adaptation", category: "soft", title: "Adaptabilidade a perfis de cliente", summary: "Ajustar ritmo, linguagem e profundidade sem abandonar clareza ou ética.", practice: "Reformule a mesma explicação para um perfil objetivo, analítico e relacional.", reference: hubspotProspecting },
  { id: "decision-patience", category: "soft", title: "Paciência no processo de decisão", summary: "Respeitar o tempo do cliente, manter follow-up útil e não forçar urgência artificial.", practice: "Crie um plano de acompanhamento com valor para três momentos possíveis de decisão.", reference: hubspotClosing },
  { id: "negotiation-confidence", category: "soft", title: "Confiança e postura ao negociar", summary: "Conduzir negociação com preparo, limites claros e escuta de objeções.", practice: "Defina objetivo, concessões permitidas, limites e pergunta de avanço para uma negociação simulada.", reference: hubspotClosing },
  { id: "clear-communication", category: "soft", title: "Comunicação clara e assertiva", summary: "Transmitir objetivo, contexto e pedido de forma objetiva e respeitosa.", practice: "Reescreva uma mensagem longa em cinco linhas: contexto, impacto, pedido, prazo e confirmação.", reference: cclSbi },
  { id: "emotional-intelligence", category: "soft", title: "Inteligência emocional", summary: "Reconhecer emoções, escolher resposta e preservar qualidade de relação sob pressão.", practice: "Antes de uma conversa difícil, nomeie gatilho, emoção, necessidade e resposta consciente.", reference: cclSbi },
  { id: "team-motivation", category: "soft", title: "Capacidade de motivar times", summary: "Conectar esforço, sentido, progresso e reconhecimento específico.", practice: "Conduza uma abertura de cinco minutos com objetivo, indicador da semana e reconhecimento factual.", reference: cclSbi },
  { id: "effective-delegation", category: "soft", title: "Delegação eficaz", summary: "Delegar resultado, contexto, autonomia, critérios e ponto de acompanhamento.", practice: "Prepare uma delegação com resultado esperado, limite de decisão, prazo e checkpoint.", reference: atlassianKanban },
  { id: "genuine-listening", category: "soft", title: "Escuta e acolhimento genuíno", summary: "Criar espaço para a outra pessoa explicar perspectiva, impedimentos e necessidades.", practice: "Pratique uma conversa com 70% de escuta e encerre validando o que foi compreendido.", reference: cclSbi },
  { id: "pressure-decision", category: "soft", title: "Tomada de decisão sob pressão", summary: "Diferenciar fato, risco e suposição antes de escolher uma ação proporcional.", practice: "Para um cenário urgente, liste fatos, opções, risco reversível e primeira ação em 10 minutos.", reference: atlassianEisenhower },
  { id: "situational-leadership", category: "soft", title: "Liderança situacional", summary: "Ajustar direção e suporte ao nível de autonomia e domínio de cada pessoa.", practice: "Compare três pessoas fictícias e defina o nível de direção, apoio e autonomia adequado.", reference: cclSbi },
  { id: "proactivity", category: "soft", title: "Proatividade", summary: "Antecipar riscos e iniciar ações úteis sem perder alinhamento com prioridades.", practice: "Escolha um risco da semana e proponha prevenção, responsável, prazo e evidência de conclusão.", reference: atlassianKanban },
  { id: "discipline-consistency", category: "soft", title: "Disciplina e consistência", summary: "Criar cadências pequenas, sustentáveis e revisáveis para hábitos de execução.", practice: "Defina um ritual de 15 minutos, um gatilho diário e uma marcação simples de execução por cinco dias.", reference: atlassianEisenhower },
  { id: "healthy-self-management", category: "soft", title: "Autogestão e autocobrança saudável", summary: "Manter exigência com limites, aprendizado e ajustes realistas.", practice: "No fim do dia, registre avanço, obstáculo, aprendizado e próximo passo sem julgamento pessoal.", reference: atlassianEisenhower },
  { id: "critical-thinking", category: "soft", title: "Pensamento crítico", summary: "Distinguir evidência, suposição, alternativa e critério de decisão.", practice: "Pegue uma hipótese de trabalho e anote evidências a favor, contra e uma forma de testá-la.", reference: atlassianKanban },
  { id: "change-flexibility", category: "soft", title: "Flexibilidade diante de mudanças", summary: "Replanejar sem perder objetivo, identificando o que muda e o que permanece.", practice: "Diante de uma alteração de cenário, defina objetivo preservado, ajuste de rota e comunicação necessária.", reference: atlassianKanban },
  { id: "ethics-responsibility", category: "soft", title: "Ética e responsabilidade no trabalho", summary: "Tomar decisões transparentes, respeitar limites e proteger informações de clientes e colegas.", practice: "Avalie um caso fictício com impactos, partes afetadas, política aplicável e ação responsável.", reference: hubspotProspecting },
];

export type SpartacusPlanInput = { hardSkillIds: string[]; softSkillIds: string[]; developmentGoal?: string; studyMinutes: number; learnerRole: "agente" | "polo" | "distrital" };

export function selectedSpartacusSkills(ids: string[], category: SpartacusSkillCategory) {
  const selected = ids.map(id => SPARTACUS_SKILLS.find(skill => skill.id === id && skill.category === category)).filter((skill): skill is SpartacusSkill => Boolean(skill));
  if (selected.length !== 3 || new Set(ids).size !== 3) throw new Error(`Selecione três ${category === "hard" ? "hard skills" : "soft skills"} diferentes.`);
  return selected;
}

export function buildSpartacusPdi(input: SpartacusPlanInput) {
  const hardSkills = selectedSpartacusSkills(input.hardSkillIds, "hard");
  const softSkills = selectedSpartacusSkills(input.softSkillIds, "soft");
  const selected = [...hardSkills, ...softSkills];
  const roleLabel = input.learnerRole === "polo" ? "Dono de Polo" : input.learnerRole === "distrital" ? "Distrital" : "Agente";
  const goal = input.developmentGoal?.trim() || "Evoluir a execução comercial com consistência, ética e reflexão sobre a prática.";
  const weeklyMissions = [
    { week: 1, title: "Diagnóstico e repertório", objective: "Estudar os princípios e observar como eles aparecem no trabalho.", sessions: selected.slice(0, 3).map(skill => `${skill.title}: ${skill.practice}`) },
    { week: 2, title: "Prática deliberada", objective: "Aplicar blocos curtos em simulações e preparar uma situação real por competência.", sessions: selected.slice(3).map(skill => `${skill.title}: ${skill.practice}`) },
    { week: 3, title: "Campo e feedback", objective: "Executar uma prática segura no trabalho, registrar evidências e pedir feedback específico.", sessions: selected.map(skill => `${skill.title}: aplique uma microação e registre o que funcionou, o que mudará e qual evidência observou.`) },
    { week: 4, title: "Consolidação", objective: "Repetir o que gerou aprendizado e transformar o desenvolvimento em rotina.", sessions: selected.map(skill => `${skill.title}: faça uma revisão de 10 minutos, defina a próxima cadência e um critério de progresso.`) },
  ];
  const references = Array.from(new Map(selected.map(skill => [skill.reference.url, skill.reference])).values());
  const conversationPrompt = `# PAPEL\nVocê é SPARTACUS, um treinador conversacional de desenvolvimento profissional para um(a) ${roleLabel}. Seu objetivo é desenvolver competências por prática deliberada, simulações realistas e feedback específico; não é substituir políticas internas, RH, jurídico, gestores ou treinamentos oficiais.\n\n# CONTEXTO DO APRENDIZ\nObjetivo de desenvolvimento: ${goal}\nHard skills selecionadas: ${hardSkills.map(skill => skill.title).join("; ")}.\nSoft skills selecionadas: ${softSkills.map(skill => skill.title).join("; ")}.\nTempo disponível por sessão: ${input.studyMinutes} minutos.\n\n# MÉTODO DE TREINO\n1. Comece fazendo até cinco perguntas de diagnóstico sobre contexto, objetivo, obstáculos e critério de sucesso. Não solicite senha, dados pessoais, informações sigilosas de clientes ou conteúdo confidencial.\n2. Escolha uma competência por vez e explique o princípio em linguagem simples, em até 120 palavras.\n3. Crie uma simulação profissional fictícia e realista. Para vendas, priorize descoberta, valor e consentimento; não sugira pressão, engano, promessa não comprovada, contato automático ou uso indevido de dados.\n4. Peça uma resposta do aprendiz. Não responda pela pessoa antes que ela tente.\n5. Dê feedback em quatro blocos: ponto forte observável; risco ou lacuna; sugestão concreta; versão para nova tentativa. Use SBI quando o exercício envolver feedback.\n6. Aumente a dificuldade gradualmente e encerre cada sessão com uma microação de campo, evidência verificável e pergunta de reflexão.\n\n# FORMATO OBRIGATÓRIO DE CADA RODADA\nCompetência | Cenário | Objetivo | Sua vez | Critérios de qualidade | Feedback após sua resposta | Microação prática.\n\n# LIMITES\nUse apenas informações fornecidas pelo aprendiz ou cenários fictícios. Declare incertezas. Em temas trabalhistas, legais, de RH ou processos formais, ofereça orientação educacional geral e recomende consulta às políticas internas e a profissionais qualificados. Preserve ética, privacidade, respeito e autonomia do interlocutor.\n\n# INÍCIO\nApresente-se em duas frases e faça a primeira pergunta de diagnóstico.`;
  const audioScript = `SPARTACUS, plano de desenvolvimento de quatro semanas. Objetivo: ${goal} Você selecionou as hard skills ${hardSkills.map(skill => skill.title).join(", ")}; e as soft skills ${softSkills.map(skill => skill.title).join(", ")}. Reserve ${input.studyMinutes} minutos por sessão. Na primeira semana, estude os fundamentos e observe oportunidades reais. Na segunda, faça simulações curtas. Na terceira, aplique uma microação segura e registre o aprendizado. Na quarta, revise evidências e transforme o que funcionou em rotina. Ao final de cada prática, responda: o que fiz, qual foi o efeito, o que ajustarei e qual será meu próximo passo?`;
  return { version: 1, title: "PDI SPARTACUS — 4 semanas", learnerRole: input.learnerRole, roleLabel, goal, studyMinutes: input.studyMinutes, hardSkills, softSkills, weeklyMissions, references, conversationPrompt, audioScript };
}
