export const portalHtml = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#070b09"><link rel="icon" href="/portal/assets/stone-sym.png"><title>Portal do Polo - Nova Odisseia</title>
<style>
:root{--g:#00a868;--g2:#00774a;--g3:#e6f6ef;--ink:#14211b;--mut:#5b6b63;--bg:#f1f5f3;--line:#dbe5df;--dark:#070b09;--r:16px}
*{box-sizing:border-box}html{scroll-behavior:smooth}
body{margin:0;font-family:"Avenir Next",Inter,"Segoe UI",system-ui,Arial,sans-serif;color:var(--ink);background-color:var(--bg);background-image:radial-gradient(#c9d8cf 1px,transparent 1px);background-size:22px 22px;min-height:100vh;display:flex;flex-direction:column}
header{background:linear-gradient(120deg,#050805 0%,#0a1510 55%,#0a2a1c 100%);color:#fff;padding:10px 22px;display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap;position:sticky;top:0;z-index:20;border-bottom:3px solid var(--g);box-shadow:0 4px 18px #0004}
.brand{display:flex;align-items:center;gap:12px}.brand img{width:46px;height:46px;border-radius:12px;object-fit:cover;box-shadow:0 0 0 2px #00a86866}
.brand h1{font-size:17px;margin:0;font-weight:800;letter-spacing:.2px}.brand small{color:#8fe0bf;font-size:12px;letter-spacing:.8px;text-transform:uppercase}
.chip{font-size:12px;background:#ffffff14;border:1px solid #ffffff26;border-radius:99px;padding:6px 12px;color:#d7efe3}
#who{display:flex;align-items:center;gap:10px;font-size:13px}.av{width:34px;height:34px;border-radius:50%;background:linear-gradient(135deg,var(--g),#005a39);display:inline-flex;align-items:center;justify-content:center;font-weight:800;font-size:13px;color:#fff;box-shadow:0 0 0 2px #ffffff30;flex:none}
#who .nm{display:flex;flex-direction:column;line-height:1.15}#who .nm small{color:#8fe0bf;font-size:11px}
main{max-width:1120px;width:100%;margin:20px auto;padding:0 14px;flex:1}
.card{background:#fff;border-radius:var(--r);padding:20px;box-shadow:0 1px 2px #0a1f1408,0 8px 24px #0a1f1410;margin-bottom:16px;border:1px solid #e8efeb;transition:box-shadow .25s,transform .25s}
.card.fx{animation:up .28s ease both}@keyframes up{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
.card h3{margin:0 0 12px;font-size:19px;display:inline-block;background:linear-gradient(transparent 62%,#00a86840 62%);padding:0 4px}
input,select,textarea,button{font:inherit;padding:10px 13px;border-radius:12px;border:1.5px solid #c5d4cb;background:#fff;color:var(--ink);transition:border-color .15s,box-shadow .15s,transform .12s,background .15s}
input:focus,select:focus,textarea:focus{outline:none;border-color:var(--g);box-shadow:0 0 0 4px #00a86826}
button{background:var(--g);color:#fff;border:0;cursor:pointer;font-weight:700;box-shadow:0 2px 0 #005a39}
button:hover{background:#00b872;transform:translateY(-1px)}button:active{transform:translateY(1px);box-shadow:none}
button.ghost{background:#fff;color:var(--g2);border:1.5px solid var(--g);box-shadow:none}button.ghost:hover{background:var(--g3)}
label{display:block;margin:12px 0 5px;font-size:13px;font-weight:700;color:var(--g2)}
.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}
.tabs button{background:#fff;color:var(--g2);border:1.5px solid #cfe3d8;box-shadow:none;border-radius:99px;padding:8px 14px;display:inline-flex;align-items:center;gap:7px;font-size:13px}
.tabs button svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
.tabs button:hover{border-color:var(--g);background:var(--g3)}
.tabs button.on{background:var(--g);color:#fff;border-color:var(--g);box-shadow:0 6px 16px #00a86855}
.sub button{font-size:12px;padding:6px 12px}
.hello{display:flex;align-items:center;gap:16px;background:linear-gradient(110deg,#00a868,#007a4d);color:#fff;border:0}
.hello .av{width:52px;height:52px;font-size:19px;background:#ffffff26}.hello h2{margin:0;font-size:22px}.hello p{margin:3px 0 0;opacity:.92;font-size:13px}.hello img{margin-left:auto;height:34px;opacity:.95}
.hello .pick{margin-left:auto;display:flex;align-items:center;gap:8px;background:#ffffff1f;border-radius:12px;padding:6px 10px}.hello .pick label{margin:0;color:#fff;font-size:12px}.hello .pick select{border:0;padding:7px 10px;font-weight:700;color:var(--g2)}
table{border-collapse:separate;border-spacing:0;width:100%;font-size:13px;border:1px solid var(--line);border-radius:12px;overflow:hidden}
td,th{border-bottom:1px solid #edf2ef;padding:7px 10px;text-align:left;vertical-align:top}tr:last-child td{border-bottom:0}
tr:first-child td{font-weight:700;background:var(--g3);color:var(--g2);position:sticky;top:0}tr:not(:first-child):hover td{background:#f4fbf7}
tr.xlf td{background:#f7faf8;padding:3px}@media print{tr.xlf{display:none}}
.wrap{overflow:auto;border-radius:12px}.err{color:#b00020;margin-top:10px;font-size:14px}.muted{color:var(--mut)}.ok{color:var(--g2);font-weight:700}
.spin{display:inline-block;width:15px;height:15px;border:2.5px solid #bfe6d3;border-top-color:var(--g);border-radius:50%;animation:rot .7s linear infinite;vertical-align:-3px;margin-right:6px}@keyframes rot{to{transform:rotate(360deg)}}
.toast{position:fixed;right:18px;bottom:18px;background:var(--dark);color:#fff;border-left:5px solid var(--g);padding:12px 16px;border-radius:12px;box-shadow:0 10px 30px #0006;max-width:340px;font-size:14px;animation:up .25s ease both;z-index:50}
.auth{display:grid;grid-template-columns:1.1fr 1fr;min-height:calc(100vh - 140px);max-width:980px;margin:10px auto;border-radius:22px;overflow:hidden;box-shadow:0 20px 60px #0a1f1430;background:#fff;animation:up .35s ease both}
.auth .hero{background:radial-gradient(circle at 30% 20%,#0d3a27,#050805 70%);color:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:34px;text-align:center;gap:14px}
.auth .hero img.em{width:min(260px,70%);border-radius:24px;animation:flt 5s ease-in-out infinite;box-shadow:0 0 60px #00a86866}@keyframes flt{50%{transform:translateY(-8px)}}
.auth .hero h2{margin:0;font-size:24px}.auth .hero p{margin:0;color:#9fe3c5;font-size:13px;letter-spacing:.7px;text-transform:uppercase}
.auth .form{padding:38px 34px;display:flex;flex-direction:column;justify-content:center}.auth .form img.st{height:34px;align-self:flex-start;margin-bottom:12px}
.auth .form h2{margin:0 0 4px}.auth .form input{width:100%}.auth .form button.big{width:100%;margin-top:16px;padding:12px}.auth a{color:var(--g2);font-weight:700;cursor:pointer;font-size:13px}
@media(max-width:760px){.auth{grid-template-columns:1fr}.auth .hero{padding:20px}.auth .hero img.em{width:120px}.hello{flex-wrap:wrap}header{position:static}}
footer{text-align:center;color:var(--mut);font-size:12px;padding:18px;display:flex;align-items:center;justify-content:center;gap:8px}footer img{height:16px;opacity:.85}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
@media print{header,.tabs,h4,input,button,.np,.muted,footer,.hello{display:none!important}body{background:#fff}.card{box-shadow:none;border:0}}
</style></head><body>
<header><div class="brand"><img src="/portal/assets/emblem.jpg" alt="Polo Vila Medeiros"><div><h1>Portal do Polo</h1><small>Vila Medeiros &middot; SP Norte</small></div></div><div id="clk" class="chip"></div><div id="who"></div></header>
<main id="app"></main>
<footer><img src="/portal/assets/stone.png" alt="Stone"> <span>Portal do Polo Vila Medeiros &middot; Nova Odisseia</span></footer>
<script src="/portal/app.js"></script></body></html>`;
export const portalJs = String.raw`
const $=s=>document.querySelector(s);const app=$('#app');let me=null,people=[],sel=null,abas=[],clients=[],tab='PSV',sub=0,visao='';
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function api(p,b){const r=await fetch('/api/portal/'+p,b?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}:{});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Erro');return j}
const EM='<img class="em" src="/portal/assets/emblem.jpg" alt="Polo Vila Medeiros">';
function authShell(inner){app.innerHTML='<div class="auth"><div class="hero">'+EM+'<h2>Polo Vila Medeiros</h2><p>SP Norte &middot; Nova Odisseia</p></div><div class="form"><img class="st" src="/portal/assets/stone.png" alt="Stone">'+inner+'</div></div>'}
const ini=n=>String(n||'?').trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function toast(m){const t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>{t.style.transition='opacity .4s';t.style.opacity=0;setTimeout(()=>t.remove(),450)},3800)}
window.alert=toast;
const IC={'PSV':'<path d="M9 5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-2"/><rect x="9" y="3" width="6" height="4" rx="1"/><path d="m9 14 2 2 4-4"/>','RMR':'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>','Vida e Onboarding':'<path d="M4.5 16.5c-1.5 1.3-2 5-2 5s3.7-.5 5-2c.7-.8.7-2.1-.1-2.9-.8-.8-2.1-.8-2.9-.1z"/><path d="m12 15-3-3a22 22 0 0 1 2-3.9A12.9 12.9 0 0 1 22 2c0 2.7-.8 7.5-6 11a22 22 0 0 1-4 2z"/>','Clientes':'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>','Links úteis':'<path d="M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7-7l-1.7 1.7"/><path d="M14 11a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7 7l1.7-1.7"/>','Materiais':'<path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>','Minha remuneração':'<circle cx="12" cy="12" r="9"/><path d="M14.8 9a2.8 2.8 0 0 0-2.8-1.5c-1.7 0-3 .9-3 2.2 0 3 6 1.5 6 4.3 0 1.3-1.3 2.2-3 2.2A3 3 0 0 1 9 14.8M12 6v2M12 16v2"/>','Meu desenvolvimento':'<path d="m22 7-8.5 8.5-5-5L2 17"/><path d="M16 7h6v6"/>','PDI':'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>','Aprendizado':'<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V3H6.5A2.5 2.5 0 0 0 4 5.5z"/><path d="M4 19.5V21h16"/>','Acessos':'<circle cx="8" cy="15" r="4"/><path d="m10.8 12.2 9-9M17 6l3 3M14 9l2 2"/>'};
const icon=t=>'<svg viewBox="0 0 24 24" aria-hidden="true">'+(IC[t]||IC[t.replace(' do polo','')]||'')+'</svg>';
function greet(){const h=parseInt(nowSP().h,10);return h<5?'Boa madrugada':h<12?'Bom dia':h<18?'Boa tarde':'Boa noite'}
function login(err,info){$('#who').innerHTML='';authShell('<h2>Entrar</h2><p class="muted" style="margin:0 0 6px">Use seu e-mail Stone.</p><label>E-mail Stone</label><input id="e" type="email" autocomplete="username"><label>Senha</label><input id="p" type="password" autocomplete="current-password"><button class="big" id="go">Entrar</button><p style="margin:14px 0 0"><a id="fg">Esqueci minha senha</a></p><p class="muted" style="font-size:12px;margin:8px 0 0">Primeiro acesso? Use o link de convite individual enviado pela liderança do polo.</p><div class="err">'+esc(err||'')+'</div>'+(info?'<div class="ok">'+esc(info)+'</div>':''));
const go=async()=>{try{const j=await api('login',{email:$('#e').value,password:$('#p').value});me=j.user;start()}catch(e){login(e.message)}};$('#go').onclick=go;$('#p').onkeydown=e=>{if(e.key==='Enter')go()};$('#fg').onclick=()=>forgot()}
function forgot(email,step,err){email=email||'';authShell(step===2?'<h2>Nova senha</h2><p class="muted" style="margin:0 0 6px">Se o e-mail estiver cadastrado, enviamos um código de 6 dígitos. Ele vale por 15 minutos.</p><label>E-mail Stone</label><input id="fe" type="email" value="'+esc(email)+'"><label>Código de 6 dígitos</label><input id="fc" inputmode="numeric" maxlength="6" autocomplete="one-time-code" style="letter-spacing:6px;font-size:20px;text-align:center"><label>Nova senha (10+ caracteres, letras e números)</label><input id="fn" type="password" autocomplete="new-password"><button class="big" id="fr">Criar senha e entrar</button><p style="margin:14px 0 0"><a id="fb">Voltar ao login</a></p><div class="err">'+esc(err||'')+'</div>':'<h2>Esqueci minha senha</h2><p class="muted" style="margin:0 0 6px">Informe seu e-mail Stone. Enviamos um código de verificação para ele.</p><label>E-mail Stone</label><input id="fe" type="email" value="'+esc(email)+'" autocomplete="username"><button class="big" id="fs">Enviar código</button><p style="margin:14px 0 0"><a id="fb">Voltar ao login</a></p><div class="err">'+esc(err||'')+'</div>');
$('#fb').onclick=()=>login();
if(step===2){$('#fr').onclick=async()=>{try{const j=await api('reset',{email:$('#fe').value,code:$('#fc').value,password:$('#fn').value});me=j.user;start()}catch(e){forgot($('#fe').value,2,e.message)}}}
else{const s=async()=>{try{await api('forgot',{email:$('#fe').value});forgot($('#fe').value,2)}catch(e){forgot($('#fe').value,1,e.message)}};$('#fs').onclick=s;$('#fe').onkeydown=e=>{if(e.key==='Enter')s()}}}
function redeemUI(tok,err){history.replaceState(null,'',location.pathname);authShell('<h2>Crie sua senha</h2><p class="muted" style="margin:0 0 6px">Este convite é pessoal e vale uma única vez.</p><label>Nova senha (10+ caracteres, letras e números)</label><input id="n" type="password" autocomplete="new-password"><button class="big" id="ok">Criar senha e entrar</button><div class="err">'+esc(err||'')+'</div>');
$('#ok').onclick=async()=>{try{const j=await api('redeem',{token:tok,password:$('#n').value});me=j.user;start()}catch(e){redeemUI(tok,e.message)}}}
function acessos(){$('#ac').innerHTML='<h3>Acessos do polo</h3><p class="muted">Gere um convite individual por pessoa e envie por canal privado. O link vale 48 horas e funciona uma única vez; quem abrir cria a própria senha. Gerar um novo convite também serve para quem esqueceu a senha.</p><table><tr><td>Pessoa</td><td>E-mail</td><td>Papel</td><td>Situação</td><td></td></tr>'+people.filter(p=>p.role!=='owner').map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+esc(p.email)+'</td><td>'+(p.role==='sdr'?'Agente SDR':'Agente')+'</td><td>'+(p.pending?'Convite pendente (aguardando primeiro acesso)':'Senha definida')+'</td><td><button data-i="'+p.id+'">Gerar convite</button><div id="lk'+p.id+'"></div></td></tr>').join('')+'</table>';
$('#ac').querySelectorAll('[data-i]').forEach(b=>b.onclick=async()=>{try{const j=await api('invite',{userId:+b.dataset.i});const u=location.origin+'/portal#convite='+j.token;$('#lk'+b.dataset.i).innerHTML='<input readonly size="44" value="'+esc(u)+'" onfocus="this.select()"><div class="muted">Vale até '+esc(new Date(j.expiresAt).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}))+'. Não será exibido de novo.</div>'}catch(e){alert(e.message)}})}
function change(err){authShell('<h2>Crie sua senha</h2><p class="muted" style="margin:0 0 6px">Por segurança, troque a senha agora.</p><label>Senha atual</label><input id="c" type="password"><label>Nova senha (8+ caracteres, letras e números)</label><input id="n" type="password"><button class="big" id="ok">Salvar senha</button><div class="err">'+esc(err||'')+'</div>');
$('#ok').onclick=async()=>{try{await api('change-password',{current:$('#c').value,next:$('#n').value});me.mustChange=false;start()}catch(e){change(e.message)}}}
async function start(){if(me.mustChange)return change();$('#who').innerHTML='<span class="av">'+esc(ini(me.name))+'</span><span class="nm">'+esc(me.name)+'<small>'+(me.role==='owner'?'dona do polo':me.role==='sdr'?'Agente SDR':'agente')+'</small></span> <button class="ghost" id="out" style="padding:6px 12px">Sair</button>';$('#out').onclick=async()=>{await api('logout',{});me=null;login()};
people=(await api('people')).people;sel=me.id;if(me.role==='owner'){if(DUAL()){visao=sessionStorage.getItem('visao')||'polo';tab=visao==='agente'?'PSV':'PSV do polo'}else{tab='PSV do polo';sel=(people.find(p=>p.role==='agent')||me).id}}await load()}
async function load(){if(me.role==='sdr'){abas=[];clients=[];tab='Agendamento';return render()}abas=(await api('data/'+sel)).abas;clients=(await api('clients/'+sel)).clients;render()}
const KIND={'Links úteis':'links','Materiais':'materiais','Aprendizado':'aprendizado'};
async function loadItems(){const k=KIND[tab];const j=await api('items/'+k);$('#it').innerHTML=(j.items.length?'<ul>'+j.items.map(i=>'<li><a href="'+esc(i.url)+'" target="_blank" rel="noopener">'+esc(i.title)+'</a> '+esc(i.note)+(j.canEdit?' <button class="ghost" data-x="'+i.id+'">Remover</button>':'')+'</li>').join('')+'</ul>':'<p class="muted">Nada cadastrado ainda.</p>')+(j.canEdit?'<h4>Adicionar</h4><input id="it1" placeholder="Título"> <input id="it2" placeholder="Link (https://...)" size="40"> <input id="it3" placeholder="Nota"> <button id="it4">Adicionar</button>':'');
if(j.canEdit){$('#it4').onclick=async()=>{try{await api('items/'+k,{title:$('#it1').value,url:$('#it2').value,note:$('#it3').value});loadItems()}catch(e){alert(e.message)}};$('#it').querySelectorAll('[data-x]').forEach(b=>b.onclick=async()=>{await fetch('/api/portal/items/'+k+'/'+b.dataset.x,{method:'DELETE'});loadItems()})}}
async function loadNote(){const n=tab==='PDI'?'pdi':'desenvolvimento';const j=await api('note/'+sel+'/'+n);$('#nt').innerHTML='<h3>'+esc(tab)+'</h3>'+(j.canEdit?'<textarea id="tx" rows="14" style="width:100%">'+esc(j.text)+'</textarea><br><button id="sv">Salvar</button> <span id="ms" class="muted"></span>':'<div style="white-space:pre-wrap">'+(esc(j.text)||'<span class="muted">O PDI ainda não foi registrado pela liderança do polo.</span>')+'</div>');
if(j.canEdit)$('#sv').onclick=async()=>{try{await fetch('/api/portal/note/'+sel+'/'+n,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('#tx').value})});$('#ms').textContent='Salvo.'}catch(e){alert('Erro')}}}
let REF=null,ROWS=[],MULT='';const NAT=['PF/MEI','PJ'],OFE=['Mais Agressivas','Agressivas','Menos Agressivas'];
const brl=v=>v===''||v==null?'':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function band(e){if(e==='')return'';if(e<7000)return'Abaixo de 7k';if([7000,15000,30000,50000,100000].includes(e))return'Limite: confirmar';return e<15000?'7-15K':e<30000?'15-30K':e<50000?'30-50K':e<100000?'50-100K':'100K+'}
function calc(r){const m=REF.mcc.find(x=>String(x[0])===String(r.mcc).trim());const e=r.tpv===''?'':Number(r.tpv);const o={cluster:m?m[2]:'',rent:m?m[3]:'',faixa:band(e),base:'',proj:'',aviso:''};
if(!r.nome&&!r.mcc&&!r.nat&&!r.ofe&&r.tpv==='')return o;
if(!r.nome||!r.mcc||!r.nat||!r.ofe||r.tpv===''){o.aviso='Preencher todos os campos';return o}
if(!m){o.aviso=REF.mcc.length?'MCC fora da base transcrita':'Tabela de MCC não carregada';return o}
if(e<7000){o.aviso='Regra abaixo de 7k não fornecida';return o}
if(o.faixa==='Limite: confirmar'){o.aviso='Inclusão do limite da faixa não confirmada';return o}
const k=o.rent+'|'+r.ofe+'|'+r.nat;const row=REF.rates.find(x=>x[0]===o.rent&&x[1]===r.ofe&&x[2]===r.nat);if(!row){o.aviso='Combinação inválida';return o}
const idx=e<15000?3:e<30000?4:e<50000?5:e<100000?6:7;o.base=row[idx];
const mu=parseFloat(String(MULT).replace(',','.'));if(MULT!==''&&!isNaN(mu)){o.proj=Math.round(o.base*mu*100)/100;o.aviso='Projeção; elegibilidade do card não validada'}else o.aviso='RV-base calculada; multiplicador não informado';return o}
async function loadRv(){REF=await api('ref');const j=await api('note/'+sel+'/calc');try{const s=JSON.parse(j.text||'{}');ROWS=s.rows||[];MULT=s.mult||''}catch(e){ROWS=[]}if(!ROWS.length)ROWS=[{nome:'',mcc:'',nat:'',ofe:'',tpv:''}];drawRv()}
function drawRv(){const cs=ROWS.map(calc);const sb=cs.reduce((a,c)=>a+(c.base===''?0:c.base),0);const sp=cs.reduce((a,c)=>a+(c.proj===''?0:c.proj),0);
$('#rv').innerHTML='<h3>Minha remuneração - Calculadora de RV</h3><p class="muted">Simulação por cliente/mês com a Nova Tabela (prints de 30/09/2026). Não é garantia de pagamento. Natureza (PF/MEI ou PJ) é obrigatória; o MCC define cluster e rentabilidade. Faixas: 7-15k, 15-30k, 30-50k, 50-100k e 100k+; valores exatos nos limites aparecem como "Limite: confirmar" até a Stone confirmar. Abaixo de 7k não há regra fornecida.</p><label>Multiplicador da projeção (opcional, ex.: 2 = 200%)</label><input id="mu" value="'+esc(MULT)+'" size="6"><div class="wrap"><table><tr><td>Cliente</td><td>MCC</td><td>Natureza</td><td>Oferta fechada</td><td>TPV projetado</td><td>Cluster</td><td>Rentab.</td><td>Faixa</td><td>RV-base/mês</td><td>RV projetada</td><td>Situação</td><td></td></tr>'+ROWS.map((r,i)=>{const c=cs[i];return'<tr><td><input data-i="'+i+'" data-k="nome" value="'+esc(r.nome)+'" size="16"></td><td><input data-i="'+i+'" data-k="mcc" value="'+esc(r.mcc)+'" size="5"></td><td><select data-i="'+i+'" data-k="nat"><option></option>'+NAT.map(n=>'<option'+(r.nat===n?' selected':'')+'>'+n+'</option>').join('')+'</select></td><td><select data-i="'+i+'" data-k="ofe"><option></option>'+OFE.map(n=>'<option'+(r.ofe===n?' selected':'')+'>'+n+'</option>').join('')+'</select></td><td><input data-i="'+i+'" data-k="tpv" value="'+esc(r.tpv)+'" size="9"></td><td>'+esc(c.cluster)+'</td><td>'+esc(c.rent)+'</td><td>'+esc(c.faixa)+'</td><td>'+brl(c.base)+'</td><td>'+brl(c.proj)+'</td><td>'+esc(c.aviso)+'</td><td><button class="ghost" data-rm="'+i+'">x</button></td></tr>'}).join('')+'</table></div><p><b>Soma RV-base: '+brl(sb)+'</b>'+(MULT!==''?' | <b>Projeção com multiplicador: '+brl(sp)+'</b>':'')+' | Linhas com alerta: '+cs.filter(c=>c.aviso&&!c.aviso.startsWith('RV-base')&&!c.aviso.startsWith('Projeção')).length+'</p><button id="ar">Adicionar cliente</button> <button id="sr">Salvar</button> <span id="rm" class="muted"></span>';
$('#rv').querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{ROWS[+el.dataset.i][el.dataset.k]=el.value;drawRv()});$('#mu').onchange=e=>{MULT=e.target.value;drawRv()};$('#rv').querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{ROWS.splice(+b.dataset.rm,1);if(!ROWS.length)ROWS=[{nome:'',mcc:'',nat:'',ofe:'',tpv:''}];drawRv()});$('#ar').onclick=()=>{ROWS.push({nome:'',mcc:'',nat:'',ofe:'',tpv:''});drawRv()};$('#sr').onclick=async()=>{await fetch('/api/portal/note/'+sel+'/calc',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:JSON.stringify({rows:ROWS,mult:MULT})})});$('#rm').textContent='Salvo.'}}
const ym=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');let SKEW=0;const MESES=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];const DIAS=['domingo','segunda','terça','quarta','quinta','sexta','sábado'];
function nowSP(){const f=new Intl.DateTimeFormat('en-GB',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,weekday:'short'});const o={};f.formatToParts(new Date(Date.now()+SKEW)).forEach(x=>o[x.type]=x.value);const wd=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(o.weekday);return{y:+o.year,m:+o.month,d:+o.day,h:o.hour==='24'?'00':o.hour,mi:o.minute,wd}}
function weekOfMonth(d){return Math.min(4,Math.ceil(d/7))}
function mlabel(y,m,off){let t=y*12+(m-1)-off;return MESES[t%12]+'/'+Math.floor(t/12)}
function clockTxt(){const n=nowSP();return DIAS[n.wd]+', '+String(n.d).padStart(2,'0')+'/'+String(n.m).padStart(2,'0')+'/'+n.y+' '+n.h+':'+n.mi+' (Brasília) | M0 = '+mlabel(n.y,n.m,0)+' | M1 = '+mlabel(n.y,n.m,1)+' | Semana '+weekOfMonth(n.d)+' do mês'}
function m0m1(){const n=nowSP();return '<p class="muted">M0 = '+mlabel(n.y,n.m,0)+' (mês atual) | M1 = '+mlabel(n.y,n.m,1)+' | M2 = '+mlabel(n.y,n.m,2)+' | Semana '+weekOfMonth(n.d)+' do mês</p>'}
function tickClock(){const e=$('#clk');if(e)e.textContent=clockTxt()}
setInterval(tickClock,30000);
let EDP=false,PSV=null,PM=(()=>{const n=nowSP();return n.y+'-'+String(n.m).padStart(2,'0')})(),PW=weekOfMonth(nowSP().d),PD=null;const TIERS=[['t30','30k'],['t50','50k'],['t100','100k'],['tx','Outros']];
function psvDefault(){const me2=people.find(p=>p.id==sel)||{};const g=/^gabriel\.fmarcantonio@/.test(me2.email||'');return{obj:'',tpvSem:'',built:'',cli:{t30:'',t50:'',t100:'',tx:''},propSem:'',propDia:'',visSem:'',visDia:'',tarDia:10,leadsSem:30,leads100:g?30:10,leads:[]}}
const pkey=()=>PM+'-w'+PW;
async function loadPsv(){EDP=false;PD=await api('psv/'+sel+'/'+pkey());PSV=Object.assign(psvDefault(),PD.plan||{});PSV.cli=Object.assign({t30:'',t50:'',t100:'',tx:''},PSV.cli||{});drawPsv()}
function monthsOpts(){const d=nowSP();const o=[];for(let i=-2;i<=1;i++){const x=new Date(d.y,d.m-1+i,1);o.push(ym(x))}return o}
function drawPsv(){const lk=PD.locked&&!EDP,R=PD.real||{};R.cli=R.cli||{};const L=PSV.leads,n100=L.filter(x=>x.tier==='100k').length;
const pin=(k,w)=>lk?esc(PSV[k]):'<input data-p="'+k+'" value="'+esc(PSV[k])+'" size="'+(w||6)+'">';
const rin=k=>lk?'<input data-r="'+k+'" value="'+esc(R[k]??'')+'" size="6">':'<span class="muted">após salvar o planejado</span>';
const rc=k=>lk?'<input data-rc="'+k+'" value="'+esc(R.cli[k]??'')+'" size="6">':'<span class="muted">-</span>';
const rows=[['Promessa de TPV da semana (R$)',pin('tpvSem',10),rin('tpvSem')],['Clientes novos - 30k',lk?esc(PSV.cli.t30):'<input data-c="t30" value="'+esc(PSV.cli.t30)+'" size="4">',rc('t30')],['Clientes novos - 50k',lk?esc(PSV.cli.t50):'<input data-c="t50" value="'+esc(PSV.cli.t50)+'" size="4">',rc('t50')],['Clientes novos - 100k',lk?esc(PSV.cli.t100):'<input data-c="t100" value="'+esc(PSV.cli.t100)+'" size="4">',rc('t100')],['Clientes novos - Outros',lk?esc(PSV.cli.tx):'<input data-c="tx" value="'+esc(PSV.cli.tx)+'" size="4">',rc('tx')],
['Propostas na semana',pin('propSem',4),rin('propSem')],['Propostas por dia',pin('propDia',4),rin('propDia')],['Visitas de venda na semana',pin('visSem',4),rin('visSem')],['Visitas de venda por dia',pin('visDia',4),rin('visDia')],['Tarefas de venda por dia (barra mín.)',pin('tarDia',3),rin('tarDia')],['Leads na semana (barra mín.)',pin('leadsSem',3),rin('leadsSem')],['Leads de 100k (barra mín.)',pin('leads100',3),rin('leads100')]];
$('#psv').innerHTML='<h3>PSV - Planejamento Semanal de Vendas</h3>'+m0m1()+'<p>Mês <select id="pm1">'+monthsOpts().map(m=>'<option'+(m===PM?' selected':'')+'>'+m+'</option>').join('')+'</select> Semana <select id="pw1">'+[1,2,3,4].map(w=>'<option value="'+w+'"'+(w===PW?' selected':'')+'>Semana '+w+'</option>').join('')+'</select> '+(PD.locked?'<b>Planejado salvo e travado em '+esc((PD.lockedAt||'').slice(0,16).replace('T',' '))+'</b>'+(PD.editedByLeaderAt?' (ajustado pela liderança em '+esc(PD.editedByLeaderAt.slice(0,16).replace('T',' '))+')':'')+(me.role==='owner'&&!EDP?' <button class="ghost" id="ed1">Editar planejado (liderança)</button>':''):'<b>Planejado em edição</b>')+'</p><p class="muted">Monte na sexta o PSV da próxima semana. Ao salvar o planejado ele trava; depois você só atualiza o Realizado. Campo em branco fica em branco.</p>'
+'<label>Objetivo da semana</label>'+(lk?'<div>'+esc(PSV.obj)+'</div>':'<input data-p="obj" value="'+esc(PSV.obj)+'" style="width:100%">')+'<label>O que já construí até agora</label>'+(lk?'<div>'+esc(PSV.built)+'</div>':'<input data-p="built" value="'+esc(PSV.built)+'" style="width:100%">')
+'<h4>Números da semana</h4><div class="wrap"><table data-noxl="1"><tr><td>Indicador</td><td>Planejado</td><td>Realizado</td></tr>'+rows.map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td></tr>').join('')+'</table></div>'
+'<h4>Lista de leads da semana</h4><p><b>'+L.length+' de '+esc(PSV.leadsSem)+' leads</b> | <b>'+n100+' de '+esc(PSV.leads100)+' de 100k</b></p><div class="wrap"><table class="xl"><tr><td>#</td><td>Lead</td><td>Tier</td><td>Obs</td><td></td></tr>'+L.map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(x.nome)+'</td><td>'+esc(x.tier)+'</td><td>'+esc(x.obs)+'</td><td>'+(lk?'':'<button class="ghost" data-lr="'+i+'">x</button>')+'</td></tr>').join('')+'</table></div>'
+(lk?'':'<input id="ln" placeholder="Nome do lead"> <select id="lt"><option>100k</option><option>50k</option><option>30k</option><option>Outro</option></select> <input id="lo" placeholder="Obs"> <button id="la">Adicionar lead</button><p class="muted">A lista vem da base de leads quando houver; por enquanto você adiciona manualmente.</p>')
+'<p>'+(lk?'<label>Realizado: o que construí</label><input data-r="built" value="'+esc(R.built??'')+'" style="width:100%"><br><br><button id="sr1">Salvar realizado</button>':'<button id="sp1">Salvar planejado (trava)</button>')+' <span id="pm" class="muted"></span></p>';
const ed=$('#ed1');if(ed)ed.onclick=()=>{EDP=true;drawPsv()};$('#pm1').onchange=e=>{PM=e.target.value;loadPsv()};$('#pw1').onchange=e=>{PW=+e.target.value;loadPsv()};
if(!lk){$('#psv').querySelectorAll('[data-p]').forEach(el=>el.onchange=()=>{PSV[el.dataset.p]=el.value;drawPsv()});$('#psv').querySelectorAll('[data-c]').forEach(el=>el.onchange=()=>{PSV.cli[el.dataset.c]=el.value});
$('#psv').querySelectorAll('[data-lr]').forEach(b=>b.onclick=()=>{PSV.leads.splice(+b.dataset.lr,1);drawPsv()});$('#la').onclick=()=>{const n=$('#ln').value.trim();if(!n)return;PSV.leads.push({nome:n,tier:$('#lt').value,obs:$('#lo').value});drawPsv()};
$('#sp1').onclick=async()=>{if(!confirm(PD.locked?'Salvar o ajuste no planejado travado?':'Salvar o planejado desta semana? Depois de salvo só a liderança do polo pode alterá-lo.'))return;const r=await fetch('/api/portal/psv/'+sel+'/'+pkey()+'/plan',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:PSV})});const j=await r.json();if(!r.ok)return alert(j.error);await loadPsv()}}
else{$('#sr1').onclick=async()=>{const d={cli:{},built:''};$('#psv').querySelectorAll('[data-r]').forEach(el=>d[el.dataset.r]=el.value);$('#psv').querySelectorAll('[data-rc]').forEach(el=>d.cli[el.dataset.rc]=el.value);const r=await fetch('/api/portal/psv/'+sel+'/'+pkey()+'/real',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:d})});const j=await r.json();if(!r.ok)return alert(j.error);PD.real=d;$('#pm').textContent='Realizado salvo.'}}
xlAll()}
let PRM=null;const PF=[['obj','Objetivo do mês (RV alvo, R$)'],['tpv','Promessa de TPV do mês (R$)'],['t30','Novos clientes 30k'],['t50','Novos clientes 50k'],['t100','Novos clientes 100k'],['prop','Propostas no mês'],['tar','Tarefas de venda no mês']];
const numb=v=>{const x=parseFloat(String(v??'').replace(/[R$\s]/g,'').replace(/\./g,'').replace(',','.'));return isNaN(x)?null:x};
function sugest(){const out={};const res=(abas.find(a=>a.aba==='Resumo')||{linhas:[]}).linhas;const rv=res.find(l=>/RV alvo/i.test(l[0]));out.obj={v:rv?String(rv[1]):'',falta:rv?'':'RV alvo não consta na planilha do agente.'};
const sem=(abas.find(a=>a.aba==='Semanas')||{linhas:[]}).linhas;const h=(sem[0]||[]).map(x=>String(x).toLowerCase());const ix=n=>h.findIndex(x=>x.startsWith(n));const sum=n=>{const i=ix(n);if(i<0)return 0;return sem.slice(1).reduce((a,r)=>a+(numb(r[i])||0),0)};
const T=sum('tarefas real'),P=sum('propostas real'),C=sum('clientes real');const cli=(PRM.man.t30!==''||PRM.man.t50!==''||PRM.man.t100!=='')?['t30','t50','t100'].reduce((a,k)=>a+(numb(PRM.man[k])||0),0):null;
const miss='Falta histórico real de propostas, tarefas e clientes fechados por semana (colunas "real" da aba Semanas estão vazias).';
out.tpv={v:'',falta:'Sem conversão de faixa (30k/50k/100k) em TPV definida; digite a promessa de TPV em R$.'};['t30','t50','t100'].forEach(k=>out[k]={v:'',falta:'Falta conversão por tier (sem histórico de propostas e fechamentos por tier).'});
if(P>0&&C>0&&cli!==null&&cli>0){out.prop={v:String(Math.ceil(cli/(C/P))),falta:'Conversão do agente: '+C+' clientes / '+P+' propostas (soma das semanas lançadas).'}}else out.prop={v:'',falta:miss+' Também precisa da meta de novos clientes acima.'};
if(out.prop.v&&T>0&&P>0){out.tar={v:String(Math.ceil(Number(out.prop.v)*(T/P))),falta:'Tarefas por proposta: '+T+' / '+P+'.'}}else out.tar={v:'',falta:miss};return out}
async function loadPrm(){const n=nowSP();const key='promessa-'+n.y+'-'+String(n.m).padStart(2,'0');const j=await api('note/'+sel+'/'+key);let o={};try{o=JSON.parse(j.text||'{}')}catch(e){}PRM={key,man:Object.assign({obj:'',tpv:'',t30:'',t50:'',t100:'',prop:'',tar:''},o.man||{})};drawPrm()}
function drawPrm(){const n=nowSP(),sg=sugest();const el=$('#prm');if(!el)return;el.innerHTML='<div class="card" style="border:1px solid #0b5d3b"><h3>Promessa do mês - '+mlabel(n.y,n.m,0)+'</h3><p class="muted">Sugestão é calculada pela conversão do agente quando há dado; sem dado fica em branco e mostra o que falta. O campo manual é o que vale. A promessa do mês não trava o planejado do PSV.</p><div class="wrap"><table data-noxl="1"><tr><td>Item</td><td>Sugestão</td><td>Minha promessa</td></tr>'+PF.map(f=>'<tr><td>'+f[1]+'</td><td>'+(sg[f[0]].v?'<b>'+esc(sg[f[0]].v)+'</b><br>':'')+'<span class="muted">'+esc(sg[f[0]].falta)+'</span></td><td><input data-m="'+f[0]+'" value="'+esc(PRM.man[f[0]])+'" size="10"></td></tr>').join('')+'</table></div><button id="pms">Salvar promessa</button> <span id="pmm" class="muted"></span></div>';
el.querySelectorAll('[data-m]').forEach(i=>i.onchange=()=>{PRM.man[i.dataset.m]=i.value;drawPrm()});$('#pms').onclick=async()=>{await fetch('/api/portal/note/'+sel+'/'+PRM.key,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:JSON.stringify({man:PRM.man})})});$('#pmm').textContent='Salvo.'}}
function xl(t){if(t.dataset.xl||t.dataset.noxl)return;t.dataset.xl='1';const rows=[...t.rows];if(rows.length<3)return;const head=rows[0],body=rows.slice(1);const n=head.cells.length;
const fr=t.insertRow(1);fr.className='xlf';for(let i=0;i<n;i++){const c=fr.insertCell();if(head.cells[i].classList.contains('np')||!head.cells[i].textContent.trim()){continue}const inp=document.createElement('input');inp.placeholder='filtrar';inp.size=8;inp.style.padding='3px 6px';inp.style.fontSize='12px';inp.oninput=apply;c.appendChild(inp)}
const dir=[];const num=v=>{const x=String(v).replace(/[R$\s%]/g,'').replace(/\./g,'').replace(',','.');return x!==''&&!isNaN(x)?parseFloat(x):null};
function apply(){const f=[...fr.cells].map(c=>c.firstChild?c.firstChild.value.trim().toLowerCase():'');body.forEach(r=>{r.style.display=f.every((v,i)=>!v||(r.cells[i]?r.cells[i].textContent.toLowerCase().includes(v):true))?'':'none'})}
for(let i=0;i<n;i++){const h=head.cells[i];if(h.classList.contains('np')||!h.textContent.trim())continue;h.style.cursor='pointer';h.title='Clique para ordenar A-Z / Z-A';h.onclick=()=>{const d=dir[i]=dir[i]==='asc'?'desc':'asc';[...head.cells].forEach(c=>c.textContent=c.textContent.replace(/ [▲▼]$/,''));h.textContent+=d==='asc'?' ▲':' ▼';const sorted=body.slice().sort((a,b)=>{const x=a.cells[i]?a.cells[i].textContent.trim():'',y=b.cells[i]?b.cells[i].textContent.trim():'';const nx=num(x),ny=num(y);let r=nx!==null&&ny!==null?nx-ny:x.localeCompare(y,'pt-BR',{numeric:true,sensitivity:'base'});return d==='asc'?r:-r});sorted.forEach(r=>t.tBodies[0].appendChild(r))}}}
function marksApply(){document.querySelectorAll('table.xl[data-aba]').forEach(async t=>{const aba=t.dataset.aba;let MK={};try{const j=await api('note/'+sel+'/marks');MK=j.text?JSON.parse(j.text):{}}catch(e){}
const rows=[...t.rows];const hi=rows.findIndex(r=>[...r.cells].some(c=>/contatad/i.test(c.textContent)));if(hi<0)return;const head=rows[hi];const ci=[...head.cells].findIndex(c=>/contatad/i.test(c.textContent));const oi=[...head.cells].findIndex(c=>/^obs/i.test(c.textContent.trim()));
head.insertCell(-1).textContent='Ativo?';let tm;const sv=()=>{clearTimeout(tm);tm=setTimeout(()=>fetch('/api/portal/note/'+sel+'/marks',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:JSON.stringify(MK)})}).then(r=>{if(!r.ok)alert('Não foi possível salvar.')}),400)};
rows.slice(hi+1).forEach(r=>{if(r.classList.contains('xlf')||r.cells.length<3||!r.cells[0].textContent.trim()){r.insertCell(-1);return}const key=aba+'|'+[0,1,2].map(i=>r.cells[i]?r.cells[i].textContent.trim():'').join('|');const m=MK[key]=MK[key]||{};const set=(k,v)=>{m[k]=v;sv()};
const orig=r.cells[ci]?r.cells[ci].textContent.trim().toLowerCase():'';if(r.cells[ci]){const c=r.cells[ci];c.textContent='';const s=document.createElement('select');[['','—'],['sim','Sim'],['nao','Não']].forEach(o=>{const op=document.createElement('option');op.value=o[0];op.textContent=o[1];s.appendChild(op)});s.value=m.c!==undefined?m.c:(orig==='sim'?'sim':/^n/.test(orig)?'nao':'');s.onchange=()=>set('c',s.value);c.appendChild(s)}
if(oi>=0&&r.cells[oi]){const c=r.cells[oi];const o0=c.textContent;c.textContent='';const i=document.createElement('input');i.size=14;i.value=m.o!==undefined?m.o:o0;i.maxLength=300;i.oninput=()=>set('o',i.value);c.appendChild(i)}
const ac=r.insertCell(-1);const cb=document.createElement('input');cb.type='checkbox';cb.checked=!!m.a;cb.title='Cliente ativo';cb.onchange=()=>set('a',cb.checked);ac.appendChild(cb)})})}
const DUAL=()=>me&&me.role==='owner'&&isG(me);const isG=p=>/^gabriel\.fmarcantonio@/.test((p&&p.email)||'');const nz=v=>{const x=numb(v);return x===null?0:x};
const PIND=[['tpvSem','Promessa de TPV da semana (R$)'],['t30','Clientes novos 30k',1],['t50','Clientes novos 50k',1],['t100','Clientes novos 100k',1],['tx','Clientes novos Outros',1],['propSem','Propostas na semana'],['visSem','Visitas de venda na semana'],['leadsSem','Leads na semana'],['leads100','Leads de 100k']];
const gv=(o,k,c)=>c?(o&&o.cli?o.cli[k]:undefined):(o?o[k]:undefined);
async function putMeta(scope,data){const r=await fetch('/api/portal/polo/meta/'+scope,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:data})});if(!r.ok){const j=await r.json().catch(()=>({}));alert(j.error||'Não foi possível salvar.')}}
function poloSel(){return '<p>Mês <select id="pm1">'+monthsOpts().map(m=>'<option'+(m===PM?' selected':'')+'>'+m+'</option>').join('')+'</select> Semana <select id="pw1">'+[1,2,3,4].map(w=>'<option value="'+w+'"'+(w===PW?' selected':'')+'>Semana '+w+'</option>').join('')+'</select></p>'}
function poloBind(re){$('#pm1').onchange=e=>{PM=e.target.value;re()};$('#pw1').onchange=e=>{PW=+e.target.value;re()}}
async function loadPolo(){const j=await api('polo/'+pkey());const A=j.agents;const meta=j.metaWeek||{};
const tot=(k,c,part)=>A.reduce((a,x)=>a+nz(gv(part==='real'?(x.real||{}):((x.plan)||{}),k,c)),0);
const fz=A.filter(x=>x.locked).length;
$('#pp').innerHTML='<h3>PSV do polo</h3>'+m0m1()+poloSel()+'<p class="muted">Consolidado dos '+A.length+' agentes do polo na semana escolhida. '+fz+' de '+A.length+' com planejado salvo. "Meta do polo" é definida por você e é separada das metas de cada agente; fica em branco até você preencher.</p>'
+'<h4>Números do polo</h4><div class="wrap"><table data-noxl="1"><tr><td>Indicador</td><td>Meta do polo</td><td>Planejado (soma dos agentes)</td><td>Realizado (soma dos agentes)</td></tr>'+PIND.map(r=>'<tr><td>'+r[1]+'</td><td><input data-pm="'+r[0]+'" value="'+esc(meta[r[0]]??'')+'" size="6"></td><td>'+tot(r[0],r[2],'plan')+'</td><td>'+tot(r[0],r[2],'real')+'</td></tr>').join('')+'</table></div>'
+'<h4>Por agente</h4><div class="wrap"><table class="xl"><tr><td>Agente</td><td>Planejado</td><td>Clientes novos (plan.)</td><td>Clientes novos (real.)</td><td>Propostas na semana (plan.)</td><td>Propostas na semana (real.)</td><td>Leads (plan.)</td></tr>'+A.map(x=>{const P=x.plan||{},R=x.real||{};const nc=o=>['t30','t50','t100','tx'].reduce((a,k)=>a+nz(gv(o,k,1)),0);return '<tr><td>'+esc(x.name)+'</td><td>'+(x.locked?'salvo':'em edição')+'</td><td>'+nc(P)+'</td><td>'+nc(R)+'</td><td>'+nz(P.propSem)+'</td><td>'+nz(R.propSem)+'</td><td>'+(P.leads?P.leads.length:0)+'</td></tr>'}).join('')+'</table></div>';
poloBind(loadPolo);$('#pp').querySelectorAll('[data-pm]').forEach(el=>el.onchange=()=>{meta[el.dataset.pm]=el.value;putMeta(pkey(),meta)});xlAll()}
async function loadPoloR(){const j=await api('polo/'+pkey());const A=j.agents;const meta=j.metaMonth||{};
const pv=(x,k)=>{const m=(x.prom&&x.prom.man)||{};return m[k]};
$('#pr').innerHTML='<h3>RMR do polo</h3>'+m0m1()+poloSel()+'<p class="muted">Promessa do mês dos '+A.length+' agentes somada. "Meta do polo" é separada das metas de agente e fica em branco até você definir. Resultado realizado do mês e causas raiz dependem dos exports do Marcopolo e ainda não estão ligados ao portal.</p>'
+'<div class="wrap"><table data-noxl="1"><tr><td>Indicador do mês</td><td>Meta do polo</td><td>Soma das promessas dos agentes</td></tr>'+PF.map(f=>'<tr><td>'+f[1]+'</td><td><input data-pm="'+f[0]+'" value="'+esc(meta[f[0]]??'')+'" size="8"></td><td>'+A.reduce((a,x)=>a+nz(pv(x,f[0])),0)+'</td></tr>').join('')+'</table></div>'
+'<h4>Promessa por agente</h4><div class="wrap"><table class="xl"><tr><td>Agente</td>'+PF.map(f=>'<td>'+f[1]+'</td>').join('')+'</tr>'+A.map(x=>'<tr><td>'+esc(x.name)+'</td>'+PF.map(f=>'<td>'+esc(pv(x,f[0])??'')+'</td>').join('')+'</tr>').join('')+'</table></div>';
poloBind(loadPoloR);$('#pr').querySelectorAll('[data-pm]').forEach(el=>el.onchange=()=>{meta[el.dataset.pm]=el.value;putMeta(PM,meta)});xlAll()}
function xlAll(){document.querySelectorAll('table.xl').forEach(xl)}
async function del(id){if(!confirm('Excluir este cliente da lista?'))return;await fetch('/api/portal/clients/'+sel+'/'+id,{method:'DELETE'});await load()}
async function addc(){const name=$('#cn').value.trim();if(!name)return alert('Informe o nome do cliente.');await api('clients/'+sel,{name,tpv:$('#ct').value,credenc:$('#cd').value,obs:$('#co').value});await load()}
const TABS=['PSV','RMR','Vida e Onboarding','Clientes','Links úteis','Materiais','Minha remuneração','Meu desenvolvimento','PDI','Aprendizado'];
function render(){let h='';const ownView=me.role==='owner'&&(!DUAL()||visao==='polo');const who=people.find(x=>x.id==sel)||me;h+='<div class="card hello fx"><span class="av">'+esc(ini(who.name))+'</span><div><h2>'+greet()+', '+esc(String(me.name).split(' ')[0])+'!</h2><p>'+(ownView?'Visão da liderança. Escolha um agente ao lado para ver os dados dele.':(me.role==='sdr'?'Painel de agendamento do Polo Vila Medeiros.':'Seu painel do Polo Vila Medeiros.'))+'</p></div>'+(ownView?'<div class="pick"><label>Agente</label><select id="sel">'+people.filter(p=>p.role!=='sdr'&&(p.role!=='owner'||(p.id===me.id&&isG(p)))).map(p=>'<option value="'+p.id+'"'+(p.id==sel?' selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select></div>':'<img src="/portal/assets/stone-white.png" alt="Stone">')+(DUAL()?'<div class="pick"><label>Visão</label><select id="vis"><option value="polo"'+(visao==='polo'?' selected':'')+'>Dono do polo</option><option value="agente"'+(visao==='agente'?' selected':'')+'>Agente</option></select></div>':'')+'</div>'
const TB=me.role==='sdr'?['Agendamento']:DUAL()?(visao==='polo'?['PSV do polo','RMR do polo','Links úteis','Materiais','Acessos']:TABS):me.role==='owner'?['PSV do polo','RMR do polo'].concat(TABS,['Acessos']):TABS;const TL=t=>(me.role==='owner'&&ownView)?({'PSV':'PSV do agente','RMR':'RMR do agente'})[t]||t:t;h+='<div class="tabs">'+TB.map(t=>'<button class="'+(t===tab?'on':'')+'" data-t="'+esc(t)+'">'+icon(t)+esc(TL(t))+'</button>').join('')+'</div><div class="card fx">';
if(tab==='Agendamento'){h+='<h3>Agendamento</h3><p>Módulo de agendamento em construção. Quando estiver pronto, ele aparece aqui.</p><p class="muted">Seu acesso é de Agente SDR: você vê apenas esta área.</p>'}
else if(tab==='PSV do polo'&&me.role==='owner'){h+='<div id="pp"><span class="spin"></span>Carregando</div>'}
else if(tab==='RMR do polo'&&me.role==='owner'){h+='<div id="pr"><span class="spin"></span>Carregando</div>'}
else if(tab==='PSV'){h+='<div id="psv"><span class="spin"></span>Carregando</div>'}
else if(tab==='RMR'||tab==='Vida e Onboarding'){h+=m0m1()+(tab==='RMR'?'<div id="prm"></div>':'');const want=tab==='RMR'?['Resumo','Semanas']:['Onboarding','Ativação','Coorte agosto','M1','Semana e vida'];const list=abas.filter(x=>want.includes(x.aba));if(!list.length)h+='<p class="muted">Sem dados importados para este perfil ainda.</p>';else{if(sub>=list.length)sub=0;h+='<div class="tabs sub">'+list.map((x,i)=>'<button class="'+(i===sub?'on':'')+'" data-s="'+i+'">'+esc(x.aba)+'</button>').join('')+'</div><div class="wrap"><table class="xl" data-aba="'+esc(list[sub].aba)+'"'+(list[sub].aba==='Resumo'?' data-noxl="1"':'')+'>'+list[sub].linhas.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</table></div><p class="muted">Dados lidos da planilha individual, sem alterações. Visível apenas para você e a liderança do polo.</p>'}}
else if(tab==='Clientes'){h+='<h3>Carteira de clientes ('+clients.length+')</h3><p class="muted">Apenas clientes credenciados sob o e-mail deste agente.</p><div class="wrap"><table class="xl" id="ct1"><tr><td>Cliente</td><td>TPV precificado</td><td>Credenc.</td><td>Origem</td><td>Obs</td><td class="np"></td></tr>'+clients.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+esc(c.tpv)+'</td><td>'+esc(c.credenc)+'</td><td>'+esc(c.origem)+'</td><td>'+esc(c.obs)+'</td><td class="np"><button class="ghost" data-d="'+c.id+'">Excluir</button></td></tr>').join('')+'</table></div><h4>Adicionar cliente</h4><input id="cn" placeholder="Nome do cliente"> <input id="ct" placeholder="TPV precificado"> <input id="cd" placeholder="Credenciamento (dd/mm)"> <input id="co" placeholder="Observação"> <button id="ca">Adicionar</button> <button class="ghost" id="cp">Exportar PDF</button>'}
else if(tab==='Links úteis'||tab==='Materiais'||tab==='Aprendizado'){h+='<div id="it"><span class="spin"></span>Carregando</div>'}
else if(tab==='PDI'||tab==='Meu desenvolvimento'){h+='<div id="nt"><span class="spin"></span>Carregando</div>'}
else if(tab==='Minha remuneração'){h+='<div id="rv"><span class="spin"></span>Carregando</div>'}
else if(tab==='Acessos'&&me.role==='owner'){h+='<div id="ac"></div>'}
else h+='<p><b>'+esc(tab)+'</b>: em construção.</p>';
h+='</div>';app.innerHTML=h;const s=$('#sel');if(s)s.onchange=async()=>{sel=+s.value;sub=0;await load()};const vs=$('#vis');if(vs)vs.onchange=async()=>{visao=vs.value;sessionStorage.setItem('visao',visao);if(visao==='agente'){sel=me.id;tab='PSV'}else{tab='PSV do polo'}sub=0;await load()};
xlAll();marksApply();if($('#pp'))loadPolo();if($('#pr'))loadPoloR();if($('#prm'))loadPrm();if($('#psv'))loadPsv();if($('#rv'))loadRv();if($('#ac'))acessos();if($('#it'))loadItems();if($('#nt'))loadNote();const ca=$('#ca');if(ca){ca.onclick=addc;$('#cp').onclick=()=>window.print();app.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>del(b.dataset.d))}
app.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{tab=b.dataset.t;render()});app.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{sub=+b.dataset.s;render()})}
fetch('/api/portal/now').then(r=>r.json()).then(j=>{SKEW=new Date(j.iso).getTime()-Date.now()}).catch(()=>{}).finally(()=>{tickClock();(location.hash.indexOf('#convite=')===0?Promise.resolve(redeemUI(location.hash.slice(9))):api('me').then(j=>{me=j.user;start()}).catch(()=>login()))});
`;
