export const portalHtml = `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Portal do Polo - Nova Odisseia</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:system-ui,Arial,sans-serif;background:#f4f6f5;color:#12301f}
header{background:#0b5d3b;color:#fff;padding:12px 20px;display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}
header h1{font-size:18px;margin:0}main{max-width:1100px;margin:18px auto;padding:0 14px}
.card{background:#fff;border-radius:10px;padding:18px;box-shadow:0 1px 4px #0002;margin-bottom:14px}
input,select,button{font:inherit;padding:9px 12px;border-radius:7px;border:1px solid #9bb;}button{background:#0b5d3b;color:#fff;border:0;cursor:pointer}
button.ghost{background:#fff;color:#0b5d3b;border:1px solid #0b5d3b}label{display:block;margin:10px 0 4px;font-size:14px}
.tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}.tabs button{background:#fff;color:#0b5d3b;border:1px solid #0b5d3b}.tabs button.on{background:#0b5d3b;color:#fff}
.sub button{font-size:13px;padding:6px 10px}table{border-collapse:collapse;width:100%;font-size:13px}td,th{border:1px solid #d5ddd8;padding:5px 8px;text-align:left;vertical-align:top}tr:first-child td{font-weight:600;background:#eef4f0}tr.xlf td{background:#f7faf8;padding:3px}@media print{tr.xlf{display:none}}
.wrap{overflow:auto}@media print{header,.tabs,h4,input,button,.np,.muted{display:none!important}body{background:#fff}.card{box-shadow:none}}.err{color:#b00020;margin-top:8px}.muted{color:#566}
</style></head><body>
<header><h1>Portal do Polo Vila Medeiros - Nova Odisseia</h1><div id="clk" style="font-size:13px"></div><div id="who"></div></header>
<main id="app"></main>
<script src="/portal/app.js"></script></body></html>`;
export const portalJs = String.raw`
const $=s=>document.querySelector(s);const app=$('#app');let me=null,people=[],sel=null,abas=[],clients=[],tab='PSV',sub=0;
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function api(p,b){const r=await fetch('/api/portal/'+p,b?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}:{});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Erro');return j}
function login(err){$('#who').innerHTML='';app.innerHTML='<div class="card" style="max-width:380px;margin:40px auto"><h2>Entrar</h2><label>E-mail Stone</label><input id="e" type="email" style="width:100%" autocomplete="username"><label>Senha</label><input id="p" type="password" style="width:100%" autocomplete="current-password"><p class="muted" style="font-size:13px">Primeiro acesso: sua senha provisória é seu primeiro nome seguido de 1 (exemplo: Gabriel1). Você vai trocá-la ao entrar.</p><button id="go">Entrar</button><div class="err">'+esc(err||'')+'</div></div>';
const go=async()=>{try{const j=await api('login',{email:$('#e').value,password:$('#p').value});me=j.user;start()}catch(e){login(e.message)}};$('#go').onclick=go;$('#p').onkeydown=e=>{if(e.key==='Enter')go()}}
function change(err){app.innerHTML='<div class="card" style="max-width:380px;margin:40px auto"><h2>Crie sua senha</h2><p>Por segurança, troque a senha provisória agora.</p><label>Senha atual</label><input id="c" type="password" style="width:100%"><label>Nova senha (8+ caracteres, letras e números)</label><input id="n" type="password" style="width:100%"><br><br><button id="ok">Salvar senha</button><div class="err">'+esc(err||'')+'</div></div>';
$('#ok').onclick=async()=>{try{await api('change-password',{current:$('#c').value,next:$('#n').value});me.mustChange=false;start()}catch(e){change(e.message)}}}
async function start(){if(me.mustChange)return change();$('#who').innerHTML=esc(me.name)+' ('+(me.role==='owner'?'dona do polo':'agente')+') <button class="ghost" id="out">Sair</button>';$('#out').onclick=async()=>{await api('logout',{});me=null;login()};
people=(await api('people')).people;sel=me.id;await load()}
async function load(){abas=(await api('data/'+sel)).abas;clients=(await api('clients/'+sel)).clients;render()}
const KIND={'Links úteis':'links','Materiais':'materiais','Aprendizado':'aprendizado'};
async function loadItems(){const k=KIND[tab];const j=await api('items/'+k);$('#it').innerHTML=(j.items.length?'<ul>'+j.items.map(i=>'<li><a href="'+esc(i.url)+'" target="_blank" rel="noopener">'+esc(i.title)+'</a> '+esc(i.note)+(j.canEdit?' <button class="ghost" data-x="'+i.id+'">Remover</button>':'')+'</li>').join('')+'</ul>':'<p class="muted">Nada cadastrado ainda.</p>')+(j.canEdit?'<h4>Adicionar</h4><input id="it1" placeholder="Título"> <input id="it2" placeholder="Link (https://...)" size="40"> <input id="it3" placeholder="Nota"> <button id="it4">Adicionar</button>':'');
if(j.canEdit){$('#it4').onclick=async()=>{try{await api('items/'+k,{title:$('#it1').value,url:$('#it2').value,note:$('#it3').value});loadItems()}catch(e){alert(e.message)}};$('#it').querySelectorAll('[data-x]').forEach(b=>b.onclick=async()=>{await fetch('/api/portal/items/'+k+'/'+b.dataset.x,{method:'DELETE'});loadItems()})}}
async function loadNote(){const n=tab==='PDI'?'pdi':'desenvolvimento';const j=await api('note/'+sel+'/'+n);$('#nt').innerHTML='<h3>'+esc(tab)+'</h3>'+(j.canEdit?'<textarea id="tx" rows="14" style="width:100%">'+esc(j.text)+'</textarea><br><button id="sv">Salvar</button> <span id="ms" class="muted"></span>':'<div style="white-space:pre-wrap">'+(esc(j.text)||'<span class="muted">O PDI ainda não foi registrado pela liderança do polo.</span>')+'</div>');
if(j.canEdit)$('#sv').onclick=async()=>{try{await fetch('/api/portal/note/'+sel+'/'+n,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('#tx').value})});$('#ms').textContent='Salvo.'}catch(e){alert('Erro')}}}
let REF=null,ROWS=[],MULT='';const NAT=['PF/MEI','PJ'],OFE=['Mais Agressivas','Agressivas','Menos Agressivas'];
const brl=v=>v===''||v==null?'':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function band(e){if(e==='')return'';if(e<7000)return'Abaixo de 7k';if([7000,15000,30000,50000,100000].includes(e))return'Limite: confirmar';return e<15000?'7-15K':e<30000?'15-30K':e<50000?'30-50K':e<100000?'50-100K':'100K+'}
function calc(r){const m=REF.mcc.find(x=>String(x[0])===String(r.mcc).trim());const e=r.tpv===''?'':Number(r.tpv);const o={cluster:m?m[2]:'',rent:m?m[3]:'',faixa:band(e),base:'',proj:'',aviso:''};
if(!r.nome&&!r.mcc&&!r.nat&&!r.ofe&&r.tpv==='')return o;
if(!r.nome||!r.mcc||!r.nat||!r.ofe||r.tpv===''){o.aviso='Preencher todos os campos';return o}
if(!m){o.aviso=REF.mcc.length?'MCC fora da base transcrita':'Tabela de MCC não carregada';return o}
if(e<7000){o.aviso='Regra abaixo de 7k não fornecida';return o}
if(o.faixa==='Limite: confirmar'){o.aviso='Inclusão do limite da faixa não confirmada';return o}
const k=o.rent+'|'+r.ofe+'|'+r.nat;const row=REF.rates.find(x=>x[0]===o.rent&&x[1]===r.ofe&&x[2]===r.nat);if(!row){o.aviso='Combinação inválida';return o}
const idx=e<15000?3:e<30000?4:e<50000?5:e<100000?6:7;o.base=row[idx];
const mu=parseFloat(String(MULT).replace(',','.'));if(MULT!==''&&!isNaN(mu)){o.proj=Math.round(o.base*mu*100)/100;o.aviso='Projeção; elegibilidade do card não validada'}else o.aviso='RV-base calculada; multiplicador não informado';return o}
async function loadRv(){REF=await api('ref');const j=await api('note/'+sel+'/calc');try{const s=JSON.parse(j.text||'{}');ROWS=s.rows||[];MULT=s.mult||''}catch(e){ROWS=[]}if(!ROWS.length)ROWS=[{nome:'',mcc:'',nat:'',ofe:'',tpv:''}];drawRv()}
function drawRv(){const cs=ROWS.map(calc);const sb=cs.reduce((a,c)=>a+(c.base===''?0:c.base),0);const sp=cs.reduce((a,c)=>a+(c.proj===''?0:c.proj),0);
$('#rv').innerHTML='<h3>Minha remuneração - Calculadora de RV</h3><p class="muted">Simulação por cliente/mês com a Nova Tabela (prints de 30/09/2026). Não é garantia de pagamento. Natureza (PF/MEI ou PJ) é obrigatória; o MCC define cluster e rentabilidade. Faixas: 7-15k, 15-30k, 30-50k, 50-100k e 100k+; valores exatos nos limites aparecem como "Limite: confirmar" até a Stone confirmar. Abaixo de 7k não há regra fornecida.</p><label>Multiplicador da projeção (opcional, ex.: 2 = 200%)</label><input id="mu" value="'+esc(MULT)+'" size="6"><div class="wrap"><table><tr><td>Cliente</td><td>MCC</td><td>Natureza</td><td>Oferta fechada</td><td>TPV projetado</td><td>Cluster</td><td>Rentab.</td><td>Faixa</td><td>RV-base/mês</td><td>RV projetada</td><td>Situação</td><td></td></tr>'+ROWS.map((r,i)=>{const c=cs[i];return'<tr><td><input data-i="'+i+'" data-k="nome" value="'+esc(r.nome)+'" size="16"></td><td><input data-i="'+i+'" data-k="mcc" value="'+esc(r.mcc)+'" size="5"></td><td><select data-i="'+i+'" data-k="nat"><option></option>'+NAT.map(n=>'<option'+(r.nat===n?' selected':'')+'>'+n+'</option>').join('')+'</select></td><td><select data-i="'+i+'" data-k="ofe"><option></option>'+OFE.map(n=>'<option'+(r.ofe===n?' selected':'')+'>'+n+'</option>').join('')+'</select></td><td><input data-i="'+i+'" data-k="tpv" value="'+esc(r.tpv)+'" size="9"></td><td>'+esc(c.cluster)+'</td><td>'+esc(c.rent)+'</td><td>'+esc(c.faixa)+'</td><td>'+brl(c.base)+'</td><td>'+brl(c.proj)+'</td><td>'+esc(c.aviso)+'</td><td><button class="ghost" data-rm="'+i+'">x</button></td></tr>'}).join('')+'</table></div><p><b>Soma RV-base: '+brl(sb)+'</b>'+(MULT!==''?' | <b>Projeção com multiplicador: '+brl(sp)+'</b>':'')+' | Linhas com alerta: '+cs.filter(c=>c.aviso&&!c.aviso.startsWith('RV-base')&&!c.aviso.startsWith('Projeção')).length+'</p><button id="ar">Adicionar cliente</button> <button id="sr">Salvar</button> <span id="rm" class="muted"></span>';
$('#rv').querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{ROWS[+el.dataset.i][el.dataset.k]=el.value;drawRv()});$('#mu').onchange=e=>{MULT=e.target.value;drawRv()};$('#rv').querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{ROWS.splice(+b.dataset.rm,1);if(!ROWS.length)ROWS=[{nome:'',mcc:'',nat:'',ofe:'',tpv:''}];drawRv()});$('#ar').onclick=()=>{ROWS.push({nome:'',mcc:'',nat:'',ofe:'',tpv:''});drawRv()};$('#sr').onclick=async()=>{await fetch('/api/portal/note/'+sel+'/calc',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:JSON.stringify({rows:ROWS,mult:MULT})})});$('#rm').textContent='Salvo.'}}
const ym=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');let SKEW=0;const MESES=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];const DIAS=['domingo','segunda','terça','quarta','quinta','sexta','sábado'];
function nowSP(){const f=new Intl.DateTimeFormat('en-GB',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,weekday:'short'});const o={};f.formatToParts(new Date(Date.now()+SKEW)).forEach(x=>o[x.type]=x.value);const wd=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(o.weekday);return{y:+o.year,m:+o.month,d:+o.day,h:o.hour==='24'?'00':o.hour,mi:o.minute,wd}}
function weekOfMonth(d){return Math.min(4,Math.ceil(d/7))}
function mlabel(y,m,off){let t=y*12+(m-1)-off;return MESES[t%12]+'/'+Math.floor(t/12)}
function clockTxt(){const n=nowSP();return DIAS[n.wd]+', '+String(n.d).padStart(2,'0')+'/'+String(n.m).padStart(2,'0')+'/'+n.y+' '+n.h+':'+n.mi+' (Brasília) | M0 = '+mlabel(n.y,n.m,0)+' | M1 = '+mlabel(n.y,n.m,1)+' | Semana '+weekOfMonth(n.d)+' do mês'}
function m0m1(){const n=nowSP();return '<p class="muted">M0 = '+mlabel(n.y,n.m,0)+' (mês atual) | M1 = '+mlabel(n.y,n.m,1)+' | M2 = '+mlabel(n.y,n.m,2)+' | Semana '+weekOfMonth(n.d)+' do mês</p>'}
function tickClock(){const e=$('#clk');if(e)e.textContent=clockTxt()}
setInterval(tickClock,30000);
let EDP=false,PSV=null,PM=(()=>{const n=nowSP();return n.y+'-'+String(n.m).padStart(2,'0')})(),PW=weekOfMonth(nowSP().d),PD=null;const TIERS=[['t30','30k'],['t50','50k'],['t100','100k'],['tx','Outros']];
function psvDefault(){const me2=people.find(p=>p.id==sel)||{};const g=/^gabriel\.fmarcantonio@/.test(me2.email||'');return{obj:'',built:'',cli:{t30:'',t50:'',t100:'',tx:''},propSem:'',propDia:'',visSem:'',visDia:'',tarDia:10,leadsSem:30,leads100:g?30:10,leads:[]}}
const pkey=()=>PM+'-w'+PW;
async function loadPsv(){EDP=false;PD=await api('psv/'+sel+'/'+pkey());PSV=Object.assign(psvDefault(),PD.plan||{});PSV.cli=Object.assign({t30:'',t50:'',t100:'',tx:''},PSV.cli||{});drawPsv()}
function monthsOpts(){const d=nowSP();const o=[];for(let i=-2;i<=1;i++){const x=new Date(d.y,d.m-1+i,1);o.push(ym(x))}return o}
function drawPsv(){const lk=PD.locked&&!EDP,R=PD.real||{};R.cli=R.cli||{};const L=PSV.leads,n100=L.filter(x=>x.tier==='100k').length;
const pin=(k,w)=>lk?esc(PSV[k]):'<input data-p="'+k+'" value="'+esc(PSV[k])+'" size="'+(w||6)+'">';
const rin=k=>lk?'<input data-r="'+k+'" value="'+esc(R[k]??'')+'" size="6">':'<span class="muted">após salvar o planejado</span>';
const rc=k=>lk?'<input data-rc="'+k+'" value="'+esc(R.cli[k]??'')+'" size="6">':'<span class="muted">-</span>';
const rows=[['Clientes novos - 30k',lk?esc(PSV.cli.t30):'<input data-c="t30" value="'+esc(PSV.cli.t30)+'" size="4">',rc('t30')],['Clientes novos - 50k',lk?esc(PSV.cli.t50):'<input data-c="t50" value="'+esc(PSV.cli.t50)+'" size="4">',rc('t50')],['Clientes novos - 100k',lk?esc(PSV.cli.t100):'<input data-c="t100" value="'+esc(PSV.cli.t100)+'" size="4">',rc('t100')],['Clientes novos - Outros',lk?esc(PSV.cli.tx):'<input data-c="tx" value="'+esc(PSV.cli.tx)+'" size="4">',rc('tx')],
['Propostas na semana',pin('propSem',4),rin('propSem')],['Propostas por dia',pin('propDia',4),rin('propDia')],['Visitas de venda na semana',pin('visSem',4),rin('visSem')],['Visitas de venda por dia',pin('visDia',4),rin('visDia')],['Tarefas de venda por dia (barra mín.)',pin('tarDia',3),rin('tarDia')],['Leads na semana (barra mín.)',pin('leadsSem',3),rin('leadsSem')],['Leads de 100k (barra mín.)',pin('leads100',3),rin('leads100')]];
$('#psv').innerHTML='<h3>PSV - Planejamento Semanal de Vendas</h3>'+m0m1()+'<p>Mês <select id="pm1">'+monthsOpts().map(m=>'<option'+(m===PM?' selected':'')+'>'+m+'</option>').join('')+'</select> Semana <select id="pw1">'+[1,2,3,4].map(w=>'<option value="'+w+'"'+(w===PW?' selected':'')+'>Semana '+w+'</option>').join('')+'</select> '+(PD.locked?'<b>Planejado salvo e travado em '+esc((PD.lockedAt||'').slice(0,16).replace('T',' '))+'</b>'+(PD.editedByLeaderAt?' (ajustado pela liderança em '+esc(PD.editedByLeaderAt.slice(0,16).replace('T',' '))+')':'')+(me.role==='owner'&&!EDP?' <button class="ghost" id="ed1">Editar planejado (liderança)</button>':''):'<b>Planejado em edição</b>')+'</p><p class="muted">Monte na sexta o PSV da próxima semana. Ao salvar o planejado ele trava; depois você só atualiza o Realizado. Campo em branco fica em branco.</p>'
+'<label>Objetivo da semana</label>'+(lk?'<div>'+esc(PSV.obj)+'</div>':'<input data-p="obj" value="'+esc(PSV.obj)+'" style="width:100%">')+'<label>O que já construí até agora</label>'+(lk?'<div>'+esc(PSV.built)+'</div>':'<input data-p="built" value="'+esc(PSV.built)+'" style="width:100%">')
+'<h4>Números da semana</h4><div class="wrap"><table data-noxl="1"><tr><td>Indicador</td><td>Planejado</td><td>Realizado</td></tr>'+rows.map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td></tr>').join('')+'</table></div>'
+'<h4>Lista de leads da semana</h4><p><b>'+L.length+' de '+esc(PSV.leadsSem)+' leads</b> | <b>'+n100+' de '+esc(PSV.leads100)+' de 100k</b></p><div class="wrap"><table class="xl"><tr><td>#</td><td>Lead</td><td>Tier</td><td>Obs</td><td></td></tr>'+L.map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(x.nome)+'</td><td>'+esc(x.tier)+'</td><td>'+esc(x.obs)+'</td><td>'+(lk?'':'<button class="ghost" data-lr="'+i+'">x</button>')+'</td></tr>').join('')+'</table></div>'
+(lk?'':'<input id="ln" placeholder="Nome do lead"> <select id="lt"><option>100k</option><option>50k</option><option>30k</option><option>Outro</option></select> <input id="lo" placeholder="Obs"> <button id="la">Adicionar lead</button><p class="muted">A lista vem da base de leads quando houver; por enquanto você adiciona manualmente.</p>')
+'<p>'+(lk?'<label>Realizado: o que construí</label><input data-r="built" value="'+esc(R.built??'')+'" style="width:100%"><br><br><button id="sr1">Salvar realizado</button>':'<button id="sp1">Salvar planejado (trava)</button>')+' <span id="pm" class="muted"></span></p>';
const ed=$('#ed1');if(ed)ed.onclick=()=>{EDP=true;drawPsv()};$('#pm1').onchange=e=>{PM=e.target.value;loadPsv()};$('#pw1').onchange=e=>{PW=+e.target.value;loadPsv()};
if(!lk){$('#psv').querySelectorAll('[data-p]').forEach(el=>el.onchange=()=>{PSV[el.dataset.p]=el.value;drawPsv()});$('#psv').querySelectorAll('[data-c]').forEach(el=>el.onchange=()=>{PSV.cli[el.dataset.c]=el.value});
$('#psv').querySelectorAll('[data-lr]').forEach(b=>b.onclick=()=>{PSV.leads.splice(+b.dataset.lr,1);drawPsv()});$('#la').onclick=()=>{const n=$('#ln').value.trim();if(!n)return;PSV.leads.push({nome:n,tier:$('#lt').value,obs:$('#lo').value});drawPsv()};
$('#sp1').onclick=async()=>{if(!confirm(PD.locked?'Salvar o ajuste no planejado travado?':'Salvar o planejado desta semana? Depois de salvo só a liderança do polo pode alterá-lo.'))return;const r=await fetch('/api/portal/psv/'+sel+'/'+pkey()+'/plan',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:PSV})});const j=await r.json();if(!r.ok)return alert(j.error);await loadPsv()}}
else{$('#sr1').onclick=async()=>{const d={cli:{},built:''};$('#psv').querySelectorAll('[data-r]').forEach(el=>d[el.dataset.r]=el.value);$('#psv').querySelectorAll('[data-rc]').forEach(el=>d.cli[el.dataset.rc]=el.value);const r=await fetch('/api/portal/psv/'+sel+'/'+pkey()+'/real',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:d})});const j=await r.json();if(!r.ok)return alert(j.error);PD.real=d;$('#pm').textContent='Realizado salvo.'}}
xlAll()}
let PRM=null;const PF=[['obj','Objetivo do mês (RV alvo, R$)'],['t30','Novos clientes 30k'],['t50','Novos clientes 50k'],['t100','Novos clientes 100k'],['prop','Propostas no mês'],['tar','Tarefas de venda no mês']];
const numb=v=>{const x=parseFloat(String(v??'').replace(/[R$\s]/g,'').replace(/\./g,'').replace(',','.'));return isNaN(x)?null:x};
function sugest(){const out={};const res=(abas.find(a=>a.aba==='Resumo')||{linhas:[]}).linhas;const rv=res.find(l=>/RV alvo/i.test(l[0]));out.obj={v:rv?String(rv[1]):'',falta:rv?'':'RV alvo não consta na planilha do agente.'};
const sem=(abas.find(a=>a.aba==='Semanas')||{linhas:[]}).linhas;const h=(sem[0]||[]).map(x=>String(x).toLowerCase());const ix=n=>h.findIndex(x=>x.startsWith(n));const sum=n=>{const i=ix(n);if(i<0)return 0;return sem.slice(1).reduce((a,r)=>a+(numb(r[i])||0),0)};
const T=sum('tarefas real'),P=sum('propostas real'),C=sum('clientes real');const cli=(PRM.man.t30!==''||PRM.man.t50!==''||PRM.man.t100!=='')?['t30','t50','t100'].reduce((a,k)=>a+(numb(PRM.man[k])||0),0):null;
const miss='Falta histórico real de propostas, tarefas e clientes fechados por semana (colunas "real" da aba Semanas estão vazias).';
['t30','t50','t100'].forEach(k=>out[k]={v:'',falta:'Falta conversão por tier (sem histórico de propostas e fechamentos por tier).'});
if(P>0&&C>0&&cli!==null&&cli>0){out.prop={v:String(Math.ceil(cli/(C/P))),falta:'Conversão do agente: '+C+' clientes / '+P+' propostas (soma das semanas lançadas).'}}else out.prop={v:'',falta:miss+' Também precisa da meta de novos clientes acima.'};
if(out.prop.v&&T>0&&P>0){out.tar={v:String(Math.ceil(Number(out.prop.v)*(T/P))),falta:'Tarefas por proposta: '+T+' / '+P+'.'}}else out.tar={v:'',falta:miss};return out}
async function loadPrm(){const n=nowSP();const key='promessa-'+n.y+'-'+String(n.m).padStart(2,'0');const j=await api('note/'+sel+'/'+key);let o={};try{o=JSON.parse(j.text||'{}')}catch(e){}PRM={key,man:Object.assign({obj:'',t30:'',t50:'',t100:'',prop:'',tar:''},o.man||{})};drawPrm()}
function drawPrm(){const n=nowSP(),sg=sugest();const el=$('#prm');if(!el)return;el.innerHTML='<div class="card" style="border:1px solid #0b5d3b"><h3>Promessa do mês - '+mlabel(n.y,n.m,0)+'</h3><p class="muted">Sugestão é calculada pela conversão do agente quando há dado; sem dado fica em branco e mostra o que falta. O campo manual é o que vale. A promessa do mês não trava o planejado do PSV.</p><div class="wrap"><table data-noxl="1"><tr><td>Item</td><td>Sugestão</td><td>Minha promessa</td></tr>'+PF.map(f=>'<tr><td>'+f[1]+'</td><td>'+(sg[f[0]].v?'<b>'+esc(sg[f[0]].v)+'</b><br>':'')+'<span class="muted">'+esc(sg[f[0]].falta)+'</span></td><td><input data-m="'+f[0]+'" value="'+esc(PRM.man[f[0]])+'" size="10"></td></tr>').join('')+'</table></div><button id="pms">Salvar promessa</button> <span id="pmm" class="muted"></span></div>';
el.querySelectorAll('[data-m]').forEach(i=>i.onchange=()=>{PRM.man[i.dataset.m]=i.value;drawPrm()});$('#pms').onclick=async()=>{await fetch('/api/portal/note/'+sel+'/'+PRM.key,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:JSON.stringify({man:PRM.man})})});$('#pmm').textContent='Salvo.'}}
async function del(id){if(!confirm('Excluir este cliente da lista?'))return;await fetch('/api/portal/clients/'+sel+'/'+id,{method:'DELETE'});await load()}
async function addc(){const name=$('#cn').value.trim();if(!name)return alert('Informe o nome do cliente.');await api('clients/'+sel,{name,tpv:$('#ct').value,credenc:$('#cd').value,obs:$('#co').value});await load()}
const TABS=['PSV','RMR','Vida e Onboarding','Clientes','Links úteis','Materiais','Minha remuneração','Meu desenvolvimento','PDI','Aprendizado'];
function render(){let h='';if(me.role==='owner'){h+='<div class="card"><label>Agente</label><select id="sel">'+people.map(p=>'<option value="'+p.id+'"'+(p.id==sel?' selected':'')+'>'+esc(p.name)+'</option>').join('')+'</select></div>'}
h+='<div class="tabs">'+TABS.map(t=>'<button class="'+(t===tab?'on':'')+'" data-t="'+esc(t)+'">'+esc(t)+'</button>').join('')+'</div><div class="card">';
if(tab==='PSV'){h+='<div id="psv">Carregando...</div>'}
else if(tab==='RMR'||tab==='Vida e Onboarding'){h+=m0m1()+(tab==='RMR'?'<div id="prm"></div>':'');const want=tab==='RMR'?['Resumo','Semanas']:['Onboarding','Ativação','Coorte agosto','M1','Semana e vida'];const list=abas.filter(x=>want.includes(x.aba));if(!list.length)h+='<p class="muted">Sem dados importados para este perfil ainda.</p>';else{if(sub>=list.length)sub=0;h+='<div class="tabs sub">'+list.map((x,i)=>'<button class="'+(i===sub?'on':'')+'" data-s="'+i+'">'+esc(x.aba)+'</button>').join('')+'</div><div class="wrap"><table class="xl"'+(list[sub].aba==='Resumo'?' data-noxl="1"':'')+'>'+list[sub].linhas.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</table></div><p class="muted">Dados lidos da planilha individual, sem alterações. Visível apenas para você e a liderança do polo.</p>'}}
else if(tab==='Clientes'){h+='<h3>Carteira de clientes ('+clients.length+')</h3><p class="muted">Apenas clientes credenciados sob o e-mail deste agente.</p><div class="wrap"><table class="xl" id="ct1"><tr><td>Cliente</td><td>TPV precificado</td><td>Credenc.</td><td>Origem</td><td>Obs</td><td class="np"></td></tr>'+clients.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+esc(c.tpv)+'</td><td>'+esc(c.credenc)+'</td><td>'+esc(c.origem)+'</td><td>'+esc(c.obs)+'</td><td class="np"><button class="ghost" data-d="'+c.id+'">Excluir</button></td></tr>').join('')+'</table></div><h4>Adicionar cliente</h4><input id="cn" placeholder="Nome do cliente"> <input id="ct" placeholder="TPV precificado"> <input id="cd" placeholder="Credenciamento (dd/mm)"> <input id="co" placeholder="Observação"> <button id="ca">Adicionar</button> <button class="ghost" id="cp">Exportar PDF</button>'}
else if(tab==='Links úteis'||tab==='Materiais'||tab==='Aprendizado'){h+='<div id="it">Carregando...</div>'}
else if(tab==='PDI'||tab==='Meu desenvolvimento'){h+='<div id="nt">Carregando...</div>'}
else if(tab==='Minha remuneração'){h+='<div id="rv">Carregando...</div>'}
else h+='<p><b>'+esc(tab)+'</b>: em construção.</p>';
h+='</div>';app.innerHTML=h;const s=$('#sel');if(s)s.onchange=async()=>{sel=+s.value;sub=0;await load()};
xlAll();if($('#prm'))loadPrm();if($('#psv'))loadPsv();if($('#rv'))loadRv();if($('#it'))loadItems();if($('#nt'))loadNote();const ca=$('#ca');if(ca){ca.onclick=addc;$('#cp').onclick=()=>window.print();app.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>del(b.dataset.d))}
app.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{tab=b.dataset.t;render()});app.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{sub=+b.dataset.s;render()})}
fetch('/api/portal/now').then(r=>r.json()).then(j=>{SKEW=new Date(j.iso).getTime()-Date.now()}).catch(()=>{}).finally(()=>{tickClock();api('me').then(j=>{me=j.user;start()}).catch(()=>login())});
`;
